import { DepartmentKPI, IndividualKPI, KPISettingsConfig } from "@/types/kpi-management";

export const MOCK_DEPARTMENT_KPIS: DepartmentKPI[] = [
  {
    id: "dept-rnd",
    departmentName: "RESEARCH & DEVELOPMENT (R&D)",
    headOfDepartment: "Dr. Hendra Wijaya",
    finalWeightedScore: 78.5,
    targetScore: 90,
    achievementPct: 87.2,
    status: "AT_RISK",
    trend: -6.0,
    lowestKpiName: "Revision Rate",
    lowestKpiScore: 56.0,
    lastCalculated: "2026-09-01 00:00",
    kpis: [
      {
        id: "kpi-rnd-1",
        name: "Sample On-Time Delivery",
        definition: "Persentase sampel formula baru yang diselesaikan tepat waktu sesuai SLA.",
        departmentId: "dept-rnd",
        departmentName: "R&D",
        weight: 25,
        target: 95,
        actual: 92,
        unit: "%",
        calcType: "HIGHER_IS_BETTER",
        achievement: 96.8,
        cappedContribution: 96.8,
        weightedScore: 24.2,
        status: "ON_TRACK",
        trend: +2.0,
        dataSource: "R&D Sample Log System",
        lastUpdate: "2026-09-01"
      },
      {
        id: "kpi-rnd-2",
        name: "Development Lead Time",
        definition: "Rata-rata hari kerja penyusunan formula baru dari brief sampai sampel fisik.",
        departmentId: "dept-rnd",
        departmentName: "R&D",
        weight: 20,
        target: 7,
        actual: 9,
        unit: "hari",
        calcType: "LOWER_IS_BETTER",
        achievement: 77.7,
        cappedContribution: 77.7,
        weightedScore: 15.5,
        status: "AT_RISK",
        trend: -1.5,
        dataSource: "R&D Lab Ticket System",
        lastUpdate: "2026-09-01"
      },
      {
        id: "kpi-rnd-3",
        name: "First Sample Approval Rate",
        definition: "Persentase sampel yang disetujui klien pada pengiriman versi pertama.",
        departmentId: "dept-rnd",
        departmentName: "R&D",
        weight: 25,
        target: 80,
        actual: 85,
        unit: "%",
        calcType: "HIGHER_IS_BETTER",
        achievement: 106.2,
        cappedContribution: 106.2,
        weightedScore: 26.5,
        status: "EXCELLENT",
        trend: +4.0,
        dataSource: "Client Feedback Audit",
        lastUpdate: "2026-09-01"
      },
      {
        id: "kpi-rnd-4",
        name: "Revision Rate",
        definition: "Tingkat revisi formula karena kesalahan teknis lab.",
        departmentId: "dept-rnd",
        departmentName: "R&D",
        weight: 20,
        target: 10,
        actual: 18,
        unit: "%",
        calcType: "LOWER_IS_BETTER",
        achievement: 55.5,
        cappedContribution: 55.5,
        weightedScore: 11.1,
        status: "OFF_TRACK",
        trend: -8.0,
        dataSource: "Lab Error Log",
        lastUpdate: "2026-09-01"
      },
      {
        id: "kpi-rnd-5",
        name: "Overdue Sample Count",
        definition: "Jumlah sampel yang tertunda lebih dari 3 hari kerja dari SLA.",
        departmentId: "dept-rnd",
        departmentName: "R&D",
        weight: 10,
        target: 2,
        actual: 3,
        unit: "count",
        calcType: "LOWER_IS_BETTER",
        achievement: 66.6,
        cappedContribution: 66.6,
        weightedScore: 6.6,
        status: "AT_RISK",
        trend: -1.0,
        dataSource: "Sample Backlog Audit",
        lastUpdate: "2026-09-01"
      }
    ]
  },
  {
    id: "dept-scm",
    departmentName: "SCM & PURCHASING",
    headOfDepartment: "Budi Santoso",
    finalWeightedScore: 91.5,
    targetScore: 90,
    achievementPct: 101.6,
    status: "ON_TRACK",
    trend: +3.5,
    lowestKpiName: "Purchase Lead Time",
    lowestKpiScore: 80.0,
    lastCalculated: "2026-09-01 00:00",
    kpis: [
      {
        id: "kpi-scm-1",
        name: "PO On-Time Creation",
        definition: "Ketepatan waktu pembuatan PO setelah PR disetujui.",
        departmentId: "dept-scm",
        departmentName: "SCM",
        weight: 25,
        target: 95,
        actual: 96,
        unit: "%",
        calcType: "HIGHER_IS_BETTER",
        achievement: 101.0,
        cappedContribution: 101.0,
        weightedScore: 25.2,
        status: "ON_TRACK",
        trend: +1.0,
        dataSource: "ERP SCM Module",
        lastUpdate: "2026-09-01"
      },
      {
        id: "kpi-scm-2",
        name: "Supplier On-Time Delivery (OTD)",
        definition: "Ketepatan waktu pengiriman bahan baku oleh vendor.",
        departmentId: "dept-scm",
        departmentName: "SCM",
        weight: 25,
        target: 90,
        actual: 93,
        unit: "%",
        calcType: "HIGHER_IS_BETTER",
        achievement: 103.3,
        cappedContribution: 103.3,
        weightedScore: 25.8,
        status: "EXCELLENT",
        trend: +5.0,
        dataSource: "Inbound Receiving Log",
        lastUpdate: "2026-09-01"
      },
      {
        id: "kpi-scm-3",
        name: "Material Availability Rate",
        definition: "Ketersediaan bahan baku kritis sebelum produksi dimulai.",
        departmentId: "dept-scm",
        departmentName: "SCM",
        weight: 25,
        target: 95,
        actual: 97,
        unit: "%",
        calcType: "HIGHER_IS_BETTER",
        achievement: 102.1,
        cappedContribution: 102.1,
        weightedScore: 25.5,
        status: "ON_TRACK",
        trend: +2.0,
        dataSource: "Warehouse Stock Reserve",
        lastUpdate: "2026-09-01"
      },
      {
        id: "kpi-scm-4",
        name: "Purchase Lead Time",
        definition: "Rata-rata lead time pemesanan sampai barang tiba di gudang.",
        departmentId: "dept-scm",
        departmentName: "SCM",
        weight: 25,
        target: 14,
        actual: 16,
        unit: "hari",
        calcType: "LOWER_IS_BETTER",
        achievement: 87.5,
        cappedContribution: 87.5,
        weightedScore: 21.8,
        status: "AT_RISK",
        trend: -2.0,
        dataSource: "Purchase History Log",
        lastUpdate: "2026-09-01"
      }
    ]
  },
  {
    id: "dept-prod",
    departmentName: "PRODUCTION",
    headOfDepartment: "Bambang Perkasa",
    finalWeightedScore: 94.0,
    targetScore: 90,
    achievementPct: 104.4,
    status: "EXCELLENT",
    trend: +4.0,
    lowestKpiName: "Defect / Rework Rate",
    lowestKpiScore: 85.0,
    lastCalculated: "2026-09-01 00:00",
    kpis: []
  },
  {
    id: "dept-bd",
    departmentName: "SALES & BUSINESS DEVELOPMENT",
    headOfDepartment: "Rian Hidayat",
    finalWeightedScore: 88.0,
    targetScore: 90,
    achievementPct: 97.7,
    status: "AT_RISK",
    trend: -1.5,
    lowestKpiName: "Stagnant Client Rate",
    lowestKpiScore: 72.0,
    lastCalculated: "2026-09-01 00:00",
    kpis: []
  },
  {
    id: "dept-qc",
    departmentName: "QUALITY CONTROL (QC/QA)",
    headOfDepartment: "Apt. Nurul Huda",
    finalWeightedScore: 96.5,
    targetScore: 90,
    achievementPct: 107.2,
    status: "EXCELLENT",
    trend: +2.0,
    lowestKpiName: "Issue Closure SLA",
    lowestKpiScore: 92.0,
    lastCalculated: "2026-09-01 00:00",
    kpis: []
  }
];

export const MOCK_INDIVIDUAL_KPIS: IndividualKPI[] = [
  {
    id: "ind-1",
    employeeId: "EMP-1001",
    employeeName: "Niko Pratama",
    department: "SCM & PURCHASING",
    role: "Purchase Staff",
    manager: "Budi Santoso",
    seniority: "STAFF",
    finalKpiScore: 86.0,
    targetScore: 90,
    status: "AT_RISK",
    trend: +2.0,
    lowestKpiName: "Purchase Lead Time",
    departmentSharedScore: 18.3, // 20% weight of Dept score (91.5 * 0.20 = 18.3)
    roleSpecificScore: 59.2, // 70% weight
    strategicProjectScore: 8.5, // 10% weight (Project ERP PO)
    lastCalculated: "2026-09-01",
    evidenceCount: 14,
    kpiItems: [
      {
        id: "k-1",
        name: "PO Creation SLA",
        definition: "Penerbitan PO tepat waktu < 24 jam.",
        departmentId: "dept-scm",
        departmentName: "SCM",
        weight: 30,
        target: 95,
        actual: 92,
        unit: "%",
        calcType: "HIGHER_IS_BETTER",
        achievement: 96.8,
        cappedContribution: 96.8,
        weightedScore: 29.0,
        status: "ON_TRACK",
        trend: +1,
        dataSource: "ERP SCM Records",
        lastUpdate: "2026-09-01"
      },
      {
        id: "k-2",
        name: "Purchase Lead Time Compliance",
        definition: "Kesesuaian lead time supplier terdaftar.",
        departmentId: "dept-scm",
        departmentName: "SCM",
        weight: 40,
        target: 14,
        actual: 17,
        unit: "hari",
        calcType: "LOWER_IS_BETTER",
        achievement: 82.3,
        cappedContribution: 82.3,
        weightedScore: 32.9,
        status: "AT_RISK",
        trend: -3,
        dataSource: "Purchase Receipt Audit",
        lastUpdate: "2026-09-01"
      }
    ]
  },
  {
    id: "ind-2",
    employeeId: "EMP-1002",
    employeeName: "Siti Aminah",
    department: "RESEARCH & DEVELOPMENT",
    role: "Formulator Senior",
    manager: "Dr. Hendra Wijaya",
    seniority: "SENIOR",
    finalKpiScore: 92.5,
    targetScore: 90,
    status: "EXCELLENT",
    trend: +4.0,
    lowestKpiName: "Development Lead Time",
    departmentSharedScore: 23.5, // 30% weight of Dept score
    roleSpecificScore: 54.0, // 50% weight
    strategicProjectScore: 15.0, // 20% weight (Winning Formula)
    lastCalculated: "2026-09-01",
    evidenceCount: 22,
    kpiItems: []
  },
  {
    id: "ind-3",
    employeeId: "EMP-1003",
    employeeName: "Budi Santoso",
    department: "SCM & PURCHASING",
    role: "Head of Purchasing",
    manager: "Direktur Utama",
    seniority: "HEAD_OF_DEPARTMENT",
    finalKpiScore: 91.5,
    targetScore: 90,
    status: "ON_TRACK",
    trend: +3.5,
    lowestKpiName: "Purchase Lead Time",
    departmentSharedScore: 54.9, // 60% weight of Dept KPI
    roleSpecificScore: 22.0, // 25% weight Strategic Projects
    strategicProjectScore: 14.6, // 15% weight Team Management
    lastCalculated: "2026-09-01",
    evidenceCount: 45,
    kpiItems: []
  }
];

export const MOCK_SETTINGS_CONFIG: KPISettingsConfig[] = [
  {
    id: "cfg-1",
    kpiName: "Sample On-Time Delivery",
    departmentName: "RESEARCH & DEVELOPMENT (R&D)",
    calcType: "HIGHER_IS_BETTER",
    dataSource: "R&D Sample Log System",
    target: 95,
    unit: "%",
    weight: 25,
    minThreshold: 80,
    maxContribution: 120,
    effectiveFrom: "2026-01-01",
    isActive: true
  },
  {
    id: "cfg-2",
    kpiName: "Development Lead Time",
    departmentName: "RESEARCH & DEVELOPMENT (R&D)",
    calcType: "LOWER_IS_BETTER",
    dataSource: "R&D Lab Ticket System",
    target: 7,
    unit: "hari",
    weight: 20,
    minThreshold: 50,
    maxContribution: 120,
    effectiveFrom: "2026-01-01",
    isActive: true
  },
  {
    id: "cfg-3",
    kpiName: "PO On-Time Creation",
    departmentName: "SCM & PURCHASING",
    calcType: "HIGHER_IS_BETTER",
    dataSource: "ERP SCM Module",
    target: 95,
    unit: "%",
    weight: 25,
    minThreshold: 85,
    maxContribution: 120,
    effectiveFrom: "2026-01-01",
    isActive: true
  }
];
