import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const url = 'http://103.93.134.215:3500';
console.log('Navigating to', url);
const resp = await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
console.log('HTTP', resp.status());
console.log('Final URL:', page.url());
await page.waitForTimeout(2000);
await page.screenshot({ path: 'C:/GAWE/Web Dev/Porto Aureon/ERP FROM ZERO/artifacts/nexerp-staging-login.png', fullPage: false });
console.log('Staging login screenshot saved');
await browser.close();
