'use client';

import { useMemo, useState } from 'react';
import { Search } from 'lucide-react';
import { DashboardCard } from '@/components/dna/DashboardCard';
import type { Client } from '@/types/marketing-overview';

export function PipelineTab({ clients, onSelect }: { clients: Client[]; onSelect: (client: Client) => void }) {
  const [query, setQuery] = useState('');
  const visible = useMemo(() => clients.filter((client) => !query || [client.name, client.company, client.stage, client.owner, client.source].some((value) => value?.toLowerCase().includes(query.toLowerCase()))), [clients, query]);
  const stages = Array.from(new Set(visible.map((client) => client.stage || 'Belum ditentukan')));
  return <div className="space-y-5" data-marketing-page="digital"><DashboardCard className="p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-base font-extrabold text-[var(--gray-900)]">Client pipeline</h2><p className="mt-1 text-xs leading-relaxed text-[var(--text-muted)]">Kanban read-only dari tahap CRM existing. Buka detail atau lanjutkan tindakan di CRM.</p></div><label className="relative w-full lg:max-w-sm"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--gray-400)]" /><span className="sr-only">Cari client pipeline</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari client, source, PIC, atau stage..." className="min-h-11 w-full rounded-xl border border-[var(--border-color)] bg-[var(--gray-50)] py-2 pl-10 pr-4 text-sm outline-none focus:border-[var(--status-action)]" /></label></div></DashboardCard><div className="flex gap-5 overflow-x-auto pb-3">{stages.map((stage) => { const entries = visible.filter((client) => (client.stage || 'Belum ditentukan') === stage); return <section key={stage} className="w-80 shrink-0 rounded-[24px] border border-[var(--border-color)] bg-[var(--gray-50)] p-3" aria-label={stage}><div className="flex items-center justify-between border-b border-[var(--border-color)] px-2 pb-3"><h3 className="text-xs font-extrabold text-[var(--gray-900)]">{stage}</h3><span className="rounded-lg bg-white px-2 py-1 text-[10px] font-extrabold text-[var(--text-muted)]">{entries.length}</span></div><div className="mt-3 space-y-3">{entries.map((client) => <button key={client.id} type="button" onClick={() => onSelect(client)} className="w-full rounded-2xl border border-[var(--border-color)] bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[var(--status-action)] focus-visible:outline-2 focus-visible:outline-[var(--status-action)]"><p className="font-bold text-[var(--gray-900)]">{client.name}</p><p className="mt-0.5 truncate text-xs text-[var(--text-muted)]">{client.company || '—'}</p><div className="mt-3 flex items-center justify-between gap-2 text-[10px] font-bold text-[var(--gray-500)]"><span className="truncate">{client.source}</span><span className="truncate">{client.owner}</span></div><p className="mt-3 truncate text-[10px] text-[var(--text-muted)]">{client.campaign || 'Belum teratribusi'}</p></button>)}</div></section>; })}</div>{!stages.length && <DashboardCard className="p-10 text-center"><p className="font-bold text-[var(--gray-900)]">Belum ada client untuk ditampilkan.</p><p className="mt-1 text-xs text-[var(--text-muted)]">Kanban akan terisi otomatis dari CRM internal.</p></DashboardCard>}</div>;
}
