#!/usr/bin/env bash
# render-table.sh — Render markdown file from template + scanned data
# Usage: bash scripts/audit/render-table.sh <page-path> <scr-id> <output-md-path>
set -u

if [ $# -lt 3 ]; then
  echo "Usage: render-table.sh <page-path> <scr-id> <output-md-path>" >&2
  exit 1
fi

PAGE="$1"
SCR_ID="$2"
OUT="$3"
ROOT="$(pwd)"

mkdir -p "$(dirname "$OUT")"

# Header
{
  echo "# Page Audit — $SCR_ID"
  echo ""
  echo "**Generated**: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "**Page**: \`$PAGE\`"
  echo ""
  bash "$ROOT/scripts/audit/compare-page-spec.sh" "$PAGE" "$SCR_ID"
  echo ""
  echo "---"
  echo ""
  echo "_Generated by \`scripts/audit/compare-page-spec.sh\`._"
} > "$OUT"

echo "Wrote: $OUT"