// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: process.env["PRISMA_SCHEMA_PATH"] || "prisma/schema",
  migrations: {
    path: process.env["PRISMA_MIGRATIONS_PATH"] || "prisma/migrations",
    seed: "ts-node --transpile-only ./prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
