import { CRMState, Stage, AutomationFlow, TrafficSourceConfig } from './types';

export const FIVE_STAGE_FUNNEL: Stage[] = [
  {
    id: 'stage_lead_masuk',
    name: 'LEADS MASUK',
    order: 1,
    color: 'slate',
    description: 'Lead baru masuk dari berbagai saluran (Meta Ads, Google Ads, Google Organic, TikTok, Linktree, Webform, Booth Tamu). Menjalankan Salesbot Ami Incoming.',
    autoTag: 'Leads Masuk',
    salesbotTrigger: 'Ami Incoming Leads New',
  },
  {
    id: 'stage_cold',
    name: 'COLD',
    order: 2,
    color: 'blue',
    description: 'Prospek baru terdata / outreach awal, belum responsif atau baru membaca profil produk.',
    autoTag: 'Cold Audience',
  },
  {
    id: 'stage_warm',
    name: 'WARM',
    order: 3,
    color: 'amber',
    description: 'Prospek tertarik aktif, konsultasi MOQ, mempelajari katalog formula, dan spesifikasi produk.',
    autoTag: 'Warm Audience',
  },
  {
    id: 'stage_hot',
    name: 'HOT',
    order: 4,
    color: 'orange',
    description: 'Prospek berkeinginan tinggi, meminta rincian HPP, penawaran harga resmi, atau jadwal meeting.',
    autoTag: 'Hot Leads',
  },
  {
    id: 'stage_sample',
    name: 'SAMPLE',
    order: 5,
    color: 'purple',
    description: 'Tahap pengiriman dan pengujian tester formulasi produk (skincare/parfum/bodycare) ke prospek.',
    autoTag: 'Sample',
  },
  {
    id: 'stage_junk_leads',
    name: 'JUNK LEADS',
    order: 6,
    color: 'rose',
    description: 'Pesan spam, penawaran pinjol/slot, nomor salah, atau kontak tidak valid yang terdeteksi otomatis dari keyword pesan.',
    autoTag: 'Junk Leads / Spam',
    isLossStage: true,
  },
  {
    id: 'stage_client_deal',
    name: 'CLIENT DEAL',
    order: 7,
    color: 'emerald',
    description: 'Prospek sepakat formula, menandatangani SPK maklon, dan melakukan pembayaran DP.',
    autoTag: 'Client Deal',
    isWonStage: true,
  },
  {
    id: 'stage_closed_lost',
    name: 'CLOSED LOST',
    order: 8,
    color: 'slate',
    description: 'Prospek ditutup gagal / tidak memenuhi kualifikasi minimum order atau budget.',
    autoTag: 'Closed Lost',
    isLossStage: true,
  },
];

export const STANDARD_STAGES: Stage[] = FIVE_STAGE_FUNNEL;

export const INITIAL_TRAFFIC_SOURCES: TrafficSourceConfig[] = [
  {
    id: 'src_website',
    name: 'Website DreamLab',
    platform: 'WEBSITE',
    utmSource: 'dreamlab.id',
    autoTag: 'Website RR Lead',
    leadCount: 0,
    totalValue: 0,
    color: 'blue',
    icon: '🌐',
    active: true,
  },
  {
    id: 'src_meta_ads',
    name: 'Meta Ads',
    platform: 'META',
    utmSource: 'facebook_instagram_ads',
    autoTag: 'Meta Ads - Ami',
    leadCount: 0,
    totalValue: 0,
    color: 'indigo',
    icon: '📱',
    active: true,
  },
  {
    id: 'src_google_ads',
    name: 'Google Ads',
    platform: 'GOOGLE',
    utmSource: 'google_search_cpc',
    autoTag: 'Google Ads - Ami',
    leadCount: 0,
    totalValue: 0,
    color: 'amber',
    icon: '🔍',
    active: true,
  },
  {
    id: 'src_google_organic',
    name: 'Google Organic',
    platform: 'GOOGLE',
    utmSource: 'google_organic_seo',
    autoTag: 'Google Organic',
    leadCount: 0,
    totalValue: 0,
    color: 'emerald',
    icon: '🌱',
    active: true,
  },
  {
    id: 'src_tiktok_ads',
    name: 'TikTok Traffic',
    platform: 'TIKTOK',
    utmSource: 'tiktok_feed_ads',
    autoTag: 'TikTok Ads',
    leadCount: 0,
    totalValue: 0,
    color: 'rose',
    icon: '🎵',
    active: true,
  },
  {
    id: 'src_wa_inbound',
    name: 'WhatsApp Inbound',
    platform: 'WHATSAPP',
    utmSource: 'wa_direct_number',
    autoTag: 'WA Inbound Direct',
    leadCount: 0,
    totalValue: 0,
    color: 'green',
    icon: '💬',
    active: true,
  },
  {
    id: 'src_link_tree',
    name: 'Link Tree',
    platform: 'WEBSITE',
    utmSource: 'linktr.ee/dreamlab',
    autoTag: 'Link Tree - Ami',
    leadCount: 0,
    totalValue: 0,
    color: 'teal',
    icon: '🌲',
    active: true,
  },
  {
    id: 'src_booth_expo',
    name: 'Buku Tamu / Offline Expo',
    platform: 'OFFLINE',
    utmSource: 'event_cosmobeaute_jcc',
    autoTag: 'Booth Expo JCC',
    leadCount: 0,
    totalValue: 0,
    color: 'purple',
    icon: '🏢',
    active: true,
  },
  {
    id: 'src_referral',
    name: 'Referral Partner',
    platform: 'REFERRAL',
    utmSource: 'b2b_referral_partner',
    autoTag: 'Referral B2B',
    leadCount: 0,
    totalValue: 0,
    color: 'sky',
    icon: '🤝',
    active: true,
  },
];

export const INITIAL_AUTOMATION_FLOWS: AutomationFlow[] = [
  {
    id: 'flow_ami_incoming_new',
    name: 'AMI INCOMING LEADS NEW',
    active: true,
    triggerEvent: 'INBOUND_MESSAGE',
    conditions: [
      {
        id: 'cond_1',
        nodeIndex: 20,
        keywordMatch: 'Halo Dreamlab, saya ingin konsultasi maklon. Bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Link Tree - Ami',
        stopBot: true,
        greetingReply: 'Halo! Terima kasih sudah menghubungi Dreamlab Maklon via Linktree. Tim BusDev kami siap membantu perhitungan HPP & konsep brand Anda.',
      },
      {
        id: 'cond_2',
        nodeIndex: 22,
        keywordMatch: 'Halo Dreamlab, saya lihat iklan di meta ads dan ingin konsultasi buat brand saya sendiri. Bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Meta Ads - Ami',
        stopBot: true,
        greetingReply: 'Halo! Terima kasih atas ketertarikan Anda melalui Meta Ads. Kami siap memandu formulasi kosmetik/skincare OEM Anda dari awal.',
      },
      {
        id: 'cond_3',
        nodeIndex: 28,
        keywordMatch: 'Hi Dreamlab saya mengetahui dari Google saya ingin konsultasi untuk brand saya, apakah bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Google Organic',
        stopBot: true,
        greetingReply: 'Halo! Selamat datang di Dreamlab Maklon melalui Google Organic. Ada kategori produk tertentu yang ingin dikembangkan?',
      },
      {
        id: 'cond_4',
        nodeIndex: 32,
        keywordMatch: 'Halo Dreamlab, saya lihat iklan di meta ads parfum dan ingin konsultasi buat brand parfum saya. Bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Meta Ads - Ami',
        stopBot: true,
        greetingReply: 'Halo! Spesialis parfum Dreamlab siap membantu kreasi bibit aroma premium & kemasan mewah untuk brand parfum Anda.',
      },
      {
        id: 'cond_5',
        nodeIndex: 35,
        keywordMatch: 'Halo Dreamlab, saya lihat iklan di meta ads haircare dan ingin konsultasi buat brand haircare saya. Bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Meta Ads - Ami',
        stopBot: true,
        greetingReply: 'Halo! Kami menyediakan sampel formulasi shampoo, hair tonic, dan serum rambut berkualitas BPOM.',
      },
      {
        id: 'cond_6',
        nodeIndex: 42,
        keywordMatch: 'Hi Dreamlab saya mengetahui dari Google Ads. Saya ingin konsultasi untuk brand saya, apakah bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Google Ads - Ami',
        stopBot: true,
        greetingReply: 'Halo! Terima kasih telah menghubungi Dreamlab via Google Ads. Tim kami siap mengirimkan katalog produk & MOQ.',
      },
      {
        id: 'cond_junk_pinjol',
        nodeIndex: 50,
        keywordMatch: 'Tawaran pinjaman online dana cepat bunga rendah tanpa agunan cair sekarang',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_junk_leads',
        autoTag: 'Junk Leads / Spam',
        stopBot: true,
        greetingReply: '',
      },
      {
        id: 'cond_junk_slot',
        nodeIndex: 51,
        keywordMatch: 'Promo link gacor deposit pulsa bonus member baru jp maxwin',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_junk_leads',
        autoTag: 'Junk Leads / Spam',
        stopBot: true,
        greetingReply: '',
      },
      {
        id: 'cond_fallback',
        nodeIndex: 39,
        keywordMatch: 'Tak satu pun dari kondisi tersebut',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Traffic Inbound',
        stopBot: true,
        isFallback: true,
        greetingReply: 'Halo, terima kasih sudah menghubungi Dreamlab! Pesan Anda telah kami terima dan akan segera dijawab oleh konsultan kami.',
      },
    ],
    fallbackTargetStageId: 'stage_lead_masuk',
    fallbackAutoTag: 'Traffic Inbound',
  },
];

export const INITIAL_STATE: CRMState = {
  trafficSources: INITIAL_TRAFFIC_SOURCES,
  pipelines: [
    {
      id: 'pipe_round_robin',
      name: 'Pipeline Round Robin (Master)',
      roundRobin: true,
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_jessica',
      name: 'Jessica (CS 1)_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: '1',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_annisa',
      name: 'Annisa (CS 2)_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: '2',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_diaz',
      name: 'Diaz (CS 3)_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: '3',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_pakbagir',
      name: 'Pak Bagir_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: '39',
      stages: FIVE_STAGE_FUNNEL,
    },
  ],
  busDevs: [
    {
      id: '1',
      name: 'Jessica (CS 1)',
      status: 'AKTIF',
      lastAssigned: null,
      leadCount: 0,
      phone: '+6287712232389',
      formattedPhone: '+62 877-1223-2389',
      role: 'BusDev Commercial Specialist',
      specialty: 'Maklon Kosmetik, Skincare & Konsultasi Brand',
      deviceModel: 'WhatsApp Bisnis #1',
    },
    {
      id: '2',
      name: 'Annisa (CS 2)',
      status: 'AKTIF',
      lastAssigned: null,
      leadCount: 0,
      phone: '+6281952417051',
      formattedPhone: '+62 819-5241-7051',
      role: 'BusDev Commercial Specialist',
      specialty: 'Maklon Kosmetik, Bodycare & Formula BPOM',
      deviceModel: 'WhatsApp Bisnis #2',
    },
    {
      id: '3',
      name: 'Diaz (CS 3)',
      status: 'AKTIF',
      lastAssigned: null,
      leadCount: 0,
      phone: '+6287776550657',
      formattedPhone: '+62 877-7655-0657',
      role: 'BusDev Commercial Specialist',
      specialty: 'Parfum, Haircare & MOQ Formulation',
      deviceModel: 'WhatsApp Bisnis #3',
    },
    {
      id: '39',
      name: 'Pak Bagir',
      status: 'AKTIF',
      lastAssigned: null,
      leadCount: 0,
      phone: '+6287766466927',
      formattedPhone: '+62 877-6646-6927',
      role: 'Head of Commercial & Partnerships',
      specialty: 'High Volume Maklon, SPK Deal & Custom OEM',
      deviceModel: 'WhatsApp Bisnis #4',
    },
  ],
  leads: [],
  messages: [],
  broadcasts: [],
  logs: [],
  automationFlows: INITIAL_AUTOMATION_FLOWS,
  activeFlowId: 'flow_ami_incoming_new',
};
