import { CRMState, Stage, AutomationFlow, TrafficSourceConfig } from './types';

export const FIVE_STAGE_FUNNEL: Stage[] = [
  {
    id: 'stage_lead_masuk',
    name: 'LEADS MASUK',
    order: 1,
    color: 'slate',
    description: 'Lead baru masuk dari berbagai saluran (Meta Ads, Google Ads, Google Organic, TikTok, Linktree, Webform, Booth Tamu). Menjalankan Salesbot Ami Incoming.',
    autoTag: 'Leads Masuk',
    salesbotTrigger: 'Ami Incoming Leads New',
  },
  {
    id: 'stage_cold',
    name: 'COLD',
    order: 2,
    color: 'blue',
    description: 'Prospek baru terdata / outreach awal, belum responsif atau baru membaca profil produk.',
    autoTag: 'Cold Audience',
  },
  {
    id: 'stage_warm',
    name: 'WARM',
    order: 3,
    color: 'amber',
    description: 'Prospek tertarik aktif, konsultasi MOQ, mempelajari katalog formula, dan spesifikasi produk.',
    autoTag: 'Warm Audience',
  },
  {
    id: 'stage_hot',
    name: 'HOT',
    order: 4,
    color: 'orange',
    description: 'Prospek berkeinginan tinggi, meminta rincian HPP, penawaran harga resmi, atau jadwal meeting.',
    autoTag: 'Hot Leads',
  },
  {
    id: 'stage_sample',
    name: 'SAMPLE',
    order: 5,
    color: 'purple',
    description: 'Tahap pengiriman dan pengujian tester formulasi produk (skincare/parfum/bodycare) ke prospek.',
    autoTag: 'Sample',
  },
  {
    id: 'stage_junk_leads',
    name: 'JUNK LEADS',
    order: 6,
    color: 'rose',
    description: 'Pesan spam, penawaran pinjol/slot, nomor salah, atau kontak tidak valid yang terdeteksi otomatis dari keyword pesan.',
    autoTag: 'Junk Leads / Spam',
    isLossStage: true,
  },
  {
    id: 'stage_client_deal',
    name: 'CLIENT DEAL',
    order: 7,
    color: 'emerald',
    description: 'Prospek sepakat formula, menandatangani SPK maklon, dan melakukan pembayaran DP.',
    autoTag: 'Client Deal',
    isWonStage: true,
  },
  {
    id: 'stage_closed_lost',
    name: 'CLOSED LOST',
    order: 8,
    color: 'slate',
    description: 'Prospek ditutup gagal / tidak memenuhi kualifikasi minimum order atau budget.',
    autoTag: 'Closed Lost',
    isLossStage: true,
  },
];

export const STANDARD_STAGES: Stage[] = FIVE_STAGE_FUNNEL;

export const INITIAL_TRAFFIC_SOURCES: TrafficSourceConfig[] = [
  {
    id: 'src_meta_ads',
    name: 'Meta Ads',
    platform: 'META',
    utmSource: 'facebook_instagram_ads',
    autoTag: 'Meta Ads - Ami',
    leadCount: 5,
    totalValue: 195000000,
    color: 'blue',
    icon: '📱',
    active: true,
  },
  {
    id: 'src_google_ads',
    name: 'Google Ads',
    platform: 'GOOGLE',
    utmSource: 'google_search_cpc',
    autoTag: 'Google Ads - Ami',
    leadCount: 4,
    totalValue: 265000000,
    color: 'amber',
    icon: '🔍',
    active: true,
  },
  {
    id: 'src_google_organic',
    name: 'Google Organic',
    platform: 'GOOGLE',
    utmSource: 'google_organic_seo',
    autoTag: 'Google Organic',
    leadCount: 2,
    totalValue: 170000000,
    color: 'emerald',
    icon: '🌐',
    active: true,
  },
  {
    id: 'src_link_tree',
    name: 'Link Tree',
    platform: 'WEBSITE',
    utmSource: 'linktr.ee/dreamlab',
    autoTag: 'Link Tree - Ami',
    leadCount: 3,
    totalValue: 185000000,
    color: 'teal',
    icon: '🌲',
    active: true,
  },
  {
    id: 'src_tiktok_ads',
    name: 'TikTok Ads',
    platform: 'TIKTOK',
    utmSource: 'tiktok_feed_ads',
    autoTag: 'TikTok Ads',
    leadCount: 2,
    totalValue: 183000000,
    color: 'rose',
    icon: '🎵',
    active: true,
  },
  {
    id: 'src_tiktok_live',
    name: 'TikTok Live',
    platform: 'TIKTOK',
    utmSource: 'tiktok_live_stream',
    autoTag: 'TikTok Live',
    leadCount: 1,
    totalValue: 30000000,
    color: 'purple',
    icon: '🎙️',
    active: true,
  },
  {
    id: 'src_wa_inbound',
    name: 'WhatsApp Inbound',
    platform: 'WHATSAPP',
    utmSource: 'wa_direct_number',
    autoTag: 'WA Inbound Direct',
    leadCount: 2,
    totalValue: 80000000,
    color: 'green',
    icon: '💬',
    active: true,
  },
  {
    id: 'src_booth_expo',
    name: 'Buku Tamu Booth Expo',
    platform: 'OFFLINE',
    utmSource: 'event_cosmobeaute_jcc',
    autoTag: 'Booth Expo JCC',
    leadCount: 2,
    totalValue: 175000000,
    color: 'indigo',
    icon: '🏢',
    active: true,
  },
  {
    id: 'src_webform',
    name: 'Webform',
    platform: 'WEBSITE',
    utmSource: 'website_contact_page',
    autoTag: 'Website Webform',
    leadCount: 1,
    totalValue: 150000000,
    color: 'cyan',
    icon: '📝',
    active: true,
  },
  {
    id: 'src_junk_leads',
    name: 'Junk Leads',
    platform: 'OTHER',
    utmSource: 'unfiltered_spam_inbound',
    autoTag: 'Junk Leads / Spam',
    leadCount: 2,
    totalValue: 0,
    color: 'slate',
    icon: '🗑️',
    active: true,
  },
  {
    id: 'src_referral',
    name: 'Referral Partner',
    platform: 'REFERRAL',
    utmSource: 'b2b_referral_partner',
    autoTag: 'Referral B2B',
    leadCount: 0,
    totalValue: 0,
    color: 'sky',
    icon: '🤝',
    active: true,
  },
];

export const INITIAL_AUTOMATION_FLOWS: AutomationFlow[] = [
  {
    id: 'flow_ami_incoming_new',
    name: 'AMI INCOMING LEADS NEW',
    active: true,
    triggerEvent: 'INBOUND_MESSAGE',
    conditions: [
      {
        id: 'cond_1',
        nodeIndex: 20,
        keywordMatch: 'Halo Dreamlab, saya ingin konsultasi maklon. Bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Link Tree - Ami',
        stopBot: true,
        greetingReply: 'Halo! Terima kasih sudah menghubungi Dreamlab Maklon via Linktree. Tim BusDev kami siap membantu perhitungan HPP & konsep brand Anda.',
      },
      {
        id: 'cond_2',
        nodeIndex: 22,
        keywordMatch: 'Halo Dreamlab, saya lihat iklan di meta ads dan ingin konsultasi buat brand saya sendiri. Bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Meta Ads - Ami',
        stopBot: true,
        greetingReply: 'Halo! Terima kasih atas ketertarikan Anda melalui Meta Ads. Kami siap memandu formulasi kosmetik/skincare OEM Anda dari awal.',
      },
      {
        id: 'cond_3',
        nodeIndex: 28,
        keywordMatch: 'Hi Dreamlab saya mengetahui dari Google saya ingin konsultasi untuk brand saya, apakah bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Google Organic',
        stopBot: true,
        greetingReply: 'Halo! Selamat datang di Dreamlab Maklon melalui Google Organic. Ada kategori produk tertentu yang ingin dikembangkan?',
      },
      {
        id: 'cond_4',
        nodeIndex: 32,
        keywordMatch: 'Halo Dreamlab, saya lihat iklan di meta ads parfum dan ingin konsultasi buat brand parfum saya. Bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Meta Ads - Ami',
        stopBot: true,
        greetingReply: 'Halo! Spesialis parfum Dreamlab siap membantu kreasi bibit aroma premium & kemasan mewah untuk brand parfum Anda.',
      },
      {
        id: 'cond_5',
        nodeIndex: 35,
        keywordMatch: 'Halo Dreamlab, saya lihat iklan di meta ads haircare dan ingin konsultasi buat brand haircare saya. Bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Meta Ads - Ami',
        stopBot: true,
        greetingReply: 'Halo! Kami menyediakan sampel formulasi shampoo, hair tonic, dan serum rambut berkualitas BPOM.',
      },
      {
        id: 'cond_6',
        nodeIndex: 42,
        keywordMatch: 'Hi Dreamlab saya mengetahui dari Google Ads. Saya ingin konsultasi untuk brand saya, apakah bisa dibantu?',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Google Ads - Ami',
        stopBot: true,
        greetingReply: 'Halo! Terima kasih telah menghubungi Dreamlab via Google Ads. Tim kami siap mengirimkan katalog produk & MOQ.',
      },
      {
        id: 'cond_junk_pinjol',
        nodeIndex: 50,
        keywordMatch: 'Tawaran pinjaman online dana cepat bunga rendah tanpa agunan cair sekarang',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_junk_leads',
        autoTag: 'Junk Leads / Spam',
        stopBot: true,
        greetingReply: '',
      },
      {
        id: 'cond_junk_slot',
        nodeIndex: 51,
        keywordMatch: 'Promo link gacor deposit pulsa bonus member baru jp maxwin',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_junk_leads',
        autoTag: 'Junk Leads / Spam',
        stopBot: true,
        greetingReply: '',
      },
      {
        id: 'cond_fallback',
        nodeIndex: 39,
        keywordMatch: 'Tak satu pun dari kondisi tersebut',
        targetPipelineId: 'pipe_round_robin',
        targetStageId: 'stage_lead_masuk',
        autoTag: 'Traffic Inbound',
        stopBot: true,
        isFallback: true,
        greetingReply: 'Halo, terima kasih sudah menghubungi Dreamlab! Pesan Anda telah kami terima dan akan segera dijawab oleh konsultan kami.',
      },
    ],
    fallbackTargetStageId: 'stage_lead_masuk',
    fallbackAutoTag: 'Traffic Inbound',
  },
];

export const INITIAL_STATE: CRMState = {
  trafficSources: INITIAL_TRAFFIC_SOURCES,
  pipelines: [
    {
      id: 'pipe_round_robin',
      name: 'Pipeline Round Robin',
      roundRobin: true,
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_diaz',
      name: 'Diaz_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: 'user_diaz',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_zaki',
      name: 'Zaki_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: 'user_zaki',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_jessica',
      name: 'Jessica_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: 'user_jessica',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_anisa',
      name: 'Anisa_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: 'user_anisa',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_irma',
      name: 'Irma_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: 'user_irma',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_bumada',
      name: 'Pipeline Busdev Bu Mada',
      roundRobin: false,
      assignedBusDevId: 'user_bumada',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_budilla',
      name: 'Bu Dilla_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: 'user_budilla',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_mutmain',
      name: 'Mutmain_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: 'user_mutmain',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_pakbagir',
      name: 'Pak Bagir_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: 'user_pakbagir',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_raka',
      name: 'Raka_Pipeline Busdev',
      roundRobin: false,
      assignedBusDevId: 'user_raka',
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_instagram',
      name: 'Pipeline Instagram Ads',
      roundRobin: true,
      stages: FIVE_STAGE_FUNNEL,
    },
    {
      id: 'pipe_tiktok',
      name: 'Pipeline TikTok Traffic',
      roundRobin: true,
      stages: FIVE_STAGE_FUNNEL,
    },
  ],
  busDevs: [
    {
      id: 'user_anisa',
      name: 'apt. Annisa Shalihah',
      status: 'AKTIF',
      lastAssigned: '2026-09-01T08:15:00Z',
      leadCount: 3,
      phone: '6281277889904',
      formattedPhone: '+62 812-7788-9904',
      role: 'BusDev Skincare & Formulasi',
      specialty: 'Skincare, Serum & Formulasi BPOM',
      deviceModel: 'Samsung S24 (WhatsApp Bisnis #01)',
    },
    {
      id: 'user_diaz',
      name: 'Diaz Pratama',
      status: 'AKTIF',
      lastAssigned: '2026-09-01T08:00:00Z',
      leadCount: 4,
      phone: '6281110001101',
      formattedPhone: '+62 811-1000-1101',
      role: 'BusDev Lead & Perfumery',
      specialty: 'Parfum Luxury & Body Mist',
      deviceModel: 'iPhone 15 Pro (WhatsApp Bisnis #02)',
    },
    {
      id: 'user_zaki',
      name: 'Zaki Alamsyah',
      status: 'AKTIF',
      lastAssigned: '2026-09-01T08:05:00Z',
      leadCount: 3,
      phone: '6281322334402',
      formattedPhone: '+62 813-2233-4402',
      role: 'BusDev Haircare & Lipcare',
      specialty: 'Haircare, Tonic, Lip Tint & Butter',
      deviceModel: 'Xiaomi 14 (WhatsApp Bisnis #03)',
    },
    {
      id: 'user_jessica',
      name: 'Jessica Tan',
      status: 'AKTIF',
      lastAssigned: '2026-09-01T08:10:00Z',
      leadCount: 2,
      phone: '6281233445503',
      formattedPhone: '+62 812-3344-5503',
      role: 'BusDev Aesthetic Clinic & OEM',
      specialty: 'Dermatology & Aesthetic Clinic MOQ',
      deviceModel: 'Samsung S23 (WhatsApp Bisnis #04)',
    },
    {
      id: 'user_bumada',
      name: 'Bu Mada Rahmawati',
      status: 'AKTIF',
      lastAssigned: '2026-09-01T08:25:00Z',
      leadCount: 3,
      phone: '6281155667706',
      formattedPhone: '+62 811-5566-7706',
      role: 'Senior BusDev Consultant',
      specialty: 'High Volume Maklon & SPK Deal',
      deviceModel: 'iPad Pro + iPhone (WhatsApp Bisnis #05)',
    },
    {
      id: 'user_irma',
      name: 'Irma Kusuma',
      status: 'AKTIF',
      lastAssigned: '2026-09-01T08:20:00Z',
      leadCount: 2,
      phone: '6281566778805',
      formattedPhone: '+62 815-6677-8805',
      role: 'BusDev Bodycare & Spa',
      specialty: 'Body Wash, Scrub, Butter & Spa',
      deviceModel: 'Vivo X100 (WhatsApp Bisnis #06)',
    },
    {
      id: 'user_budilla',
      name: 'Bu Dilla Safitri',
      status: 'AKTIF',
      lastAssigned: '2026-09-01T08:30:00Z',
      leadCount: 1,
      phone: '6281788990007',
      formattedPhone: '+62 817-8899-0007',
      role: 'BusDev Herbal & Halal Beauty',
      specialty: 'Halal Certified & Natural Cosmetics',
      deviceModel: 'Oppo Find (WhatsApp Bisnis #07)',
    },
    {
      id: 'user_mutmain',
      name: 'Mutmainah',
      status: 'AKTIF',
      lastAssigned: '2026-09-01T08:35:00Z',
      leadCount: 1,
      phone: '6281899001108',
      formattedPhone: '+62 818-9900-1108',
      role: 'BusDev Hotel Amenities',
      specialty: 'B2B Corporate & Amenities Maklon',
      deviceModel: 'Samsung A55 (WhatsApp Bisnis #08)',
    },
    {
      id: 'user_pakbagir',
      name: 'Pak Bagir Maulana',
      status: 'AKTIF',
      lastAssigned: '2026-09-01T08:40:00Z',
      leadCount: 1,
      phone: '6281900112209',
      formattedPhone: '+62 819-0011-2209',
      role: 'BusDev Soap & Hygiene',
      specialty: 'Bar Soap, Cleanser & Personal Hygiene',
      deviceModel: 'Redmi Note 13 (WhatsApp Bisnis #09)',
    },
    {
      id: 'user_raka',
      name: 'Raka Wirayuda',
      status: 'AKTIF',
      lastAssigned: '2026-09-01T08:45:00Z',
      leadCount: 2,
      phone: '6281211223310',
      formattedPhone: '+62 812-1122-3310',
      role: 'BusDev Sunscreen & Men Grooming',
      specialty: 'Sunscreen Gel, Serum & Pomade',
      deviceModel: 'Samsung S22 (WhatsApp Bisnis #10)',
    },
  ],
  leads: [],
  messages: [],
  broadcasts: [],
  logs: [
    {
      id: 'log_init',
      action: 'system_reset',
      timestamp: '2026-09-01T08:00:00Z',
      params: {},
      resultSummary: 'Database OmniCRM siap: 13 Pipelines, 5-Stage Core Funnel (LEADS MASUK - COLD - WARM - HOT - SAMPLE - CLIENT DEAL) & Realtime WhatsApp Gateway.',
      structuredOutput: {
        status: 'SUCCESS',
        pipelinesCount: 13,
        stages: 'LEADS MASUK -> COLD -> WARM -> HOT -> SAMPLE',
        sourcesCount: 10,
        leadsCount: 0,
      },
    },
  ],
  automationFlows: INITIAL_AUTOMATION_FLOWS,
  activeFlowId: 'flow_ami_incoming_new',
};
