export interface ProjectMonitoringRndRecord {
  id: string;
  no: string;
  projectName: string;
  pic: string;
  client: string;
  status: string;
  tglNpfMasuk: string;
  tglSelesai: string;
  tglPengiriman: string;
  totalPengerjaan: string;
  folderFormula: string;
  notes: string;
}

export const INITIAL_PROJECT_MONITORING_RND: ProjectMonitoringRndRecord[] = [
  {
    "id": "PROJ-RND-1",
    "no": "1",
    "projectName": "DOSTING WHITENING GLOWING NIGHT CREAM",
    "pic": "Panca",
    "client": "Gyska Puteri Casytha Purba (Ghimarow)",
    "status": "Terkirim",
    "tglNpfMasuk": "7/29/2026",
    "tglSelesai": "8/3/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-2",
    "no": "2",
    "projectName": "Sunscreen physical",
    "pic": "Panca",
    "client": "Yanti",
    "status": "Terkirim",
    "tglNpfMasuk": "7/29/2026",
    "tglSelesai": "8/3/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-3",
    "no": "3",
    "projectName": "Protein Hair Cream",
    "pic": "Panca",
    "client": "Eric W",
    "status": "Terkirim",
    "tglNpfMasuk": "7/29/2026",
    "tglSelesai": "8/4/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-4",
    "no": "4",
    "projectName": "2 in 1 MOIST & SUNSCREEN FOR MEN",
    "pic": "Panca",
    "client": "Ari Nugroho",
    "status": "Terkirim",
    "tglNpfMasuk": "8/3/2026",
    "tglSelesai": "8/5/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-5",
    "no": "5",
    "projectName": "TWIST (EDP TOM FORD OUD WOOD)",
    "pic": "Panca",
    "client": "Gadis (rini)",
    "status": "Terkirim",
    "tglNpfMasuk": "8/3/2026",
    "tglSelesai": "8/6/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-6",
    "no": "6",
    "projectName": "TWIST (EDP LV SABLES ROSE)",
    "pic": "Panca",
    "client": "Gadis (rini)",
    "status": "Terkirim",
    "tglNpfMasuk": "8/3/2026",
    "tglSelesai": "8/6/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-7",
    "no": "7",
    "projectName": "Body lotion brightening with UV filter",
    "pic": "Panca",
    "client": "fionna",
    "status": "Terkirim",
    "tglNpfMasuk": "8/3/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-8",
    "no": "8",
    "projectName": "Body lotion brighterning",
    "pic": "Panca",
    "client": "fionna",
    "status": "Terkirim",
    "tglNpfMasuk": "8/3/2026",
    "tglSelesai": "8/5/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-9",
    "no": "9",
    "projectName": "SHAMPOO BAR FORMULA 1",
    "pic": "Yaya",
    "client": "Diana",
    "status": "Terkirim",
    "tglNpfMasuk": "8/3/2026",
    "tglSelesai": "8/27/2026",
    "tglPengiriman": "8/31/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-10",
    "no": "10",
    "projectName": "SHAMPOO BAR FORMULA 2 (+ KEMIRI OIL)",
    "pic": "Yaya",
    "client": "Diana",
    "status": "Terkirim",
    "tglNpfMasuk": "8/3/2026",
    "tglSelesai": "8/27/2026",
    "tglPengiriman": "8/31/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-11",
    "no": "11",
    "projectName": "MJB Beauty Tinted Sunscreen F1",
    "pic": "Yaya",
    "client": "Paramita (MJB Beauty)",
    "status": "Terkirim",
    "tglNpfMasuk": "8/3/2026",
    "tglSelesai": "8/5/2026",
    "tglPengiriman": "8/5/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-12",
    "no": "12",
    "projectName": "MOIST CICAPLAST",
    "pic": "Yaya",
    "client": "Efriana",
    "status": "Terkirim",
    "tglNpfMasuk": "8/6/2026",
    "tglSelesai": "8/12/2026",
    "tglPengiriman": "8/13/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-13",
    "no": "13",
    "projectName": "Moisturizer Glow Finish",
    "pic": "Yaya",
    "client": "Rizaldo",
    "status": "Terkirim",
    "tglNpfMasuk": "8/6/2026",
    "tglSelesai": "8/10/2026",
    "tglPengiriman": "8/10/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-14",
    "no": "14",
    "projectName": "Prioritas Deo Stick",
    "pic": "Yaya",
    "client": "I Gusti Komang Windu Saputra",
    "status": "Terkirim",
    "tglNpfMasuk": "8/6/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "8/20/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-15",
    "no": "15",
    "projectName": "Custom Parfum EDP",
    "pic": "Yaya",
    "client": "Febiola Dani",
    "status": "Terkirim",
    "tglNpfMasuk": "8/6/2026",
    "tglSelesai": "8/7/2026",
    "tglPengiriman": "8/10/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-16",
    "no": "16",
    "projectName": "EDP Woman #2",
    "pic": "Yaya",
    "client": "Neil Royan",
    "status": "Terkirim",
    "tglNpfMasuk": "8/5/2026",
    "tglSelesai": "8/7/2026",
    "tglPengiriman": "8/10/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-17",
    "no": "17",
    "projectName": "EXTRAIT CUSTOM AROMA 2 #1",
    "pic": "Yaya",
    "client": "PT AJUNG",
    "status": "Terkirim",
    "tglNpfMasuk": "8/5/2026",
    "tglSelesai": "8/7/2026",
    "tglPengiriman": "8/10/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-18",
    "no": "18",
    "projectName": "Sunscreen serum 3in1",
    "pic": "Yaya",
    "client": "Susanti Theodore",
    "status": "Terkirim",
    "tglNpfMasuk": "8/5/2026",
    "tglSelesai": "8/12/2026",
    "tglPengiriman": "8/13/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-19",
    "no": "19",
    "projectName": "EXTRAIT PARFUM CARD ROUGE",
    "pic": "Yaya",
    "client": "Moch Ikrima",
    "status": "Terkirim",
    "tglNpfMasuk": "8/7/2026",
    "tglSelesai": "8/10/2026",
    "tglPengiriman": "8/10/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-20",
    "no": "20",
    "projectName": "Brightening Day Lotion with UV Protection #1",
    "pic": "Yaya",
    "client": "Rindhy Angraeny",
    "status": "Terkirim",
    "tglNpfMasuk": "8/7/2026",
    "tglSelesai": "8/11/2026",
    "tglPengiriman": "8/13/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-21",
    "no": "21",
    "projectName": "Night Lotion With AHA #1",
    "pic": "Yaya",
    "client": "Rindhy Angraeny",
    "status": "Terkirim",
    "tglNpfMasuk": "8/7/2026",
    "tglSelesai": "8/11/2026",
    "tglPengiriman": "8/13/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-22",
    "no": "22",
    "projectName": "White body lotion",
    "pic": "Panca",
    "client": "Risma Pujayani",
    "status": "Terkirim",
    "tglNpfMasuk": "8/5/2026",
    "tglSelesai": "8/7/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-23",
    "no": "23",
    "projectName": "Deodorant Roll On KIDS",
    "pic": "Panca",
    "client": "Rini",
    "status": "Terkirim",
    "tglNpfMasuk": "8/6/2026",
    "tglSelesai": "8/12/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-24",
    "no": "24",
    "projectName": "Serum White&Rejuve",
    "pic": "Panca",
    "client": "Honesty Cahyaningrum",
    "status": "Terkirim",
    "tglNpfMasuk": "8/6/2026",
    "tglSelesai": "8/10/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-25",
    "no": "25",
    "projectName": "Body lotion",
    "pic": "Panca",
    "client": "Yanti",
    "status": "Terkirim",
    "tglNpfMasuk": "8/7/2026",
    "tglSelesai": "8/13/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-26",
    "no": "26",
    "projectName": "CUSTOM DIOR ROSE & ROSE'S",
    "pic": "Yaya",
    "client": "Desyani Sarodjie",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "8/20/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-27",
    "no": "27",
    "projectName": "CUSTOM BULGARI ROSE GOLDEA",
    "pic": "Yaya",
    "client": "Desyani Sarodjie",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "8/20/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-28",
    "no": "28",
    "projectName": "INSPIRED LV SABLE ROSE",
    "pic": "Yaya",
    "client": "Desyani Sarodjie",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "8/20/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-29",
    "no": "29",
    "projectName": "Parfum Inspired (4 Varian 1 NPF)",
    "pic": "Yaya",
    "client": "Arfan",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "8/20/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-30",
    "no": "30",
    "projectName": "Parfum Inspired (4 Varian 1 NPF)",
    "pic": "Yaya",
    "client": "Arfan",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "8/20/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-31",
    "no": "31",
    "projectName": "Parfum Inspired (4 Varian 1 NPF)",
    "pic": "Yaya",
    "client": "Arfan",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "8/20/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-32",
    "no": "32",
    "projectName": "Parfum Inspired (4 Varian 1 NPF)",
    "pic": "Yaya",
    "client": "Arfan",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "8/20/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-33",
    "no": "33",
    "projectName": "extrait parfum le labo",
    "pic": "Yaya",
    "client": "Lala Parfum 150826",
    "status": "Pending",
    "tglNpfMasuk": "8/19/2026",
    "tglSelesai": "",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-34",
    "no": "34",
    "projectName": "moisturizer",
    "pic": "Yaya",
    "client": "windi septiana",
    "status": "Terkirim",
    "tglNpfMasuk": "8/19/2026",
    "tglSelesai": "8/21/2026",
    "tglPengiriman": "8/26/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-35",
    "no": "35",
    "projectName": "night cream",
    "pic": "Yaya",
    "client": "windi septiana",
    "status": "Terkirim",
    "tglNpfMasuk": "8/19/2026",
    "tglSelesai": "8/21/2026",
    "tglPengiriman": "8/26/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-36",
    "no": "36",
    "projectName": "face wash",
    "pic": "Yaya",
    "client": "windi septiana",
    "status": "Terkirim",
    "tglNpfMasuk": "8/19/2026",
    "tglSelesai": "8/24/2026",
    "tglPengiriman": "8/26/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-37",
    "no": "37",
    "projectName": "Shower Gel Anna Sui #1",
    "pic": "Yaya",
    "client": "Rindhy Angraeny",
    "status": "Terkirim",
    "tglNpfMasuk": "8/20/2026",
    "tglSelesai": "8/27/2026",
    "tglPengiriman": "8/31/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-38",
    "no": "38",
    "projectName": "Shower Gel Blooming Bouquet #1",
    "pic": "Yaya",
    "client": "Rindhy Angraeny",
    "status": "Terkirim",
    "tglNpfMasuk": "8/20/2026",
    "tglSelesai": "8/27/2026",
    "tglPengiriman": "8/31/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-39",
    "no": "39",
    "projectName": "ALVAREA SUNSCREEN SPRAY",
    "pic": "Yaya",
    "client": "Redy Wijaya",
    "status": "Terkirim",
    "tglNpfMasuk": "8/24/2026",
    "tglSelesai": "8/27/2026",
    "tglPengiriman": "8/31/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-40",
    "no": "40",
    "projectName": "ALVAREA BODY LOTION",
    "pic": "Yaya",
    "client": "Redy Wijaya",
    "status": "Terkirim",
    "tglNpfMasuk": "8/24/2026",
    "tglSelesai": "8/27/2026",
    "tglPengiriman": "8/31/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-41",
    "no": "41",
    "projectName": "ALVAREA SERUM DNA SALMON",
    "pic": "Yaya",
    "client": "Redy Wijaya",
    "status": "Terkirim",
    "tglNpfMasuk": "8/24/2026",
    "tglSelesai": "8/28/2026",
    "tglPengiriman": "8/31/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-42",
    "no": "42",
    "projectName": "ALVAREA LIP SERUM",
    "pic": "Yaya",
    "client": "Redy Wijaya",
    "status": "Terkirim",
    "tglNpfMasuk": "8/24/2026",
    "tglSelesai": "8/31/2026",
    "tglPengiriman": "8/31/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-43",
    "no": "43",
    "projectName": "Moist Skin barrier",
    "pic": "Yaya",
    "client": "ELMEDIKA (Benedict rafael )",
    "status": "Terkirim",
    "tglNpfMasuk": "8/24/2026",
    "tglSelesai": "9/1/2026",
    "tglPengiriman": "9/3/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-44",
    "no": "44",
    "projectName": "MOisturizer pencerah",
    "pic": "Yaya",
    "client": "ELMEDIKA (Benedict rafael )",
    "status": "Terkirim",
    "tglNpfMasuk": "8/24/2026",
    "tglSelesai": "9/1/2026",
    "tglPengiriman": "9/3/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-45",
    "no": "45",
    "projectName": "sunscreen harian ultralight",
    "pic": "Yaya",
    "client": "ELMEDIKA (Benedict rafael )",
    "status": "Terkirim",
    "tglNpfMasuk": "8/24/2026",
    "tglSelesai": "9/2/2026",
    "tglPengiriman": "9/3/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-46",
    "no": "46",
    "projectName": "facial cleanser lembut harian",
    "pic": "Yaya",
    "client": "ELMEDIKA (Benedict rafael )",
    "status": "Terkirim",
    "tglNpfMasuk": "8/24/2026",
    "tglSelesai": "9/3/2026",
    "tglPengiriman": "9/3/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-47",
    "no": "47",
    "projectName": "Brightening & dark spot serum (Tambahan sample)",
    "pic": "Yaya",
    "client": "dr. Jessika Nughraheni",
    "status": "Terkirim",
    "tglNpfMasuk": "8/26/2026",
    "tglSelesai": "8/26/2026",
    "tglPengiriman": "8/26/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-48",
    "no": "48",
    "projectName": "RREL11 DEO STICK",
    "pic": "Yaya",
    "client": "Berlin / Farrel",
    "status": "Terkirim",
    "tglNpfMasuk": "8/27/2026",
    "tglSelesai": "9/4/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-49",
    "no": "49",
    "projectName": "RREL11 BODY WASH FOR MEN",
    "pic": "Yaya",
    "client": "Berlin / Farrel",
    "status": "Terkirim",
    "tglNpfMasuk": "8/27/2026",
    "tglSelesai": "9/3/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-50",
    "no": "50",
    "projectName": "RREL11 SHAMPOO",
    "pic": "Yaya",
    "client": "Berlin / Farrel",
    "status": "Terkirim",
    "tglNpfMasuk": "8/27/2026",
    "tglSelesai": "9/3/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-51",
    "no": "51",
    "projectName": "Keep Me Thayyib Velvet Blurring Lip",
    "pic": "Yaya",
    "client": "Choulah",
    "status": "Terkirim",
    "tglNpfMasuk": "8/27/2026",
    "tglSelesai": "8/27/2026",
    "tglPengiriman": "8/29/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-52",
    "no": "52",
    "projectName": "R1 WHITE RICE",
    "pic": "Yaya",
    "client": "Randy Fadly",
    "status": "Terkirim",
    "tglNpfMasuk": "8/31/2026",
    "tglSelesai": "9/4/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-53",
    "no": "53",
    "projectName": "H1 HOJICHA",
    "pic": "Yaya",
    "client": "Randy Fadly",
    "status": "Terkirim",
    "tglNpfMasuk": "8/31/2026",
    "tglSelesai": "9/4/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-54",
    "no": "54",
    "projectName": "P1 DARK PLUM",
    "pic": "Yaya",
    "client": "Randy Fadly",
    "status": "Terkirim",
    "tglNpfMasuk": "8/31/2026",
    "tglSelesai": "9/4/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-55",
    "no": "55",
    "projectName": "EXTRAIT Zara wonder Rose dan EDP Zara wonder Rose",
    "pic": "Yaya",
    "client": "Amel Tangerang",
    "status": "Terkirim",
    "tglNpfMasuk": "8/31/2026",
    "tglSelesai": "9/3/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-56",
    "no": "56",
    "projectName": "EXTRAIT ysl libre le parfume DAN EDP ysl libre le parfume",
    "pic": "Yaya",
    "client": "Amel Tangerang",
    "status": "Terkirim",
    "tglNpfMasuk": "8/31/2026",
    "tglSelesai": "9/3/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-57",
    "no": "57",
    "projectName": "Extrait Dior Jadore L'or parfume dan EDP Dior Jadore L'or parfume",
    "pic": "Yaya",
    "client": "Amel Tangerang",
    "status": "Terkirim",
    "tglNpfMasuk": "8/31/2026",
    "tglSelesai": "9/4/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-58",
    "no": "58",
    "projectName": "EXTRAIT ALT Baron parfume Dan EDP ALT Baron parfume",
    "pic": "Yaya",
    "client": "Amel Tangerang",
    "status": "Terkirim",
    "tglNpfMasuk": "8/31/2026",
    "tglSelesai": "9/3/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-59",
    "no": "59",
    "projectName": "Extrait ALT Midnight Thorn dan EDP ALT Midnight Thorn",
    "pic": "Yaya",
    "client": "Amel Tangerang",
    "status": "Terkirim",
    "tglNpfMasuk": "8/31/2026",
    "tglSelesai": "9/4/2026",
    "tglPengiriman": "9/7/2026",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-60",
    "no": "60",
    "projectName": "PRIO-Daily Barrier Lotion KIDS (face&body)",
    "pic": "Panca",
    "client": "PT Hasil Alam Maheswara",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/19/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-61",
    "no": "61",
    "projectName": "HAIR TONIC SPRAY",
    "pic": "Panca",
    "client": "fionna",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-62",
    "no": "62",
    "projectName": "HAIR GROWTH SERUM",
    "pic": "Panca",
    "client": "fionna",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/20/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-63",
    "no": "63",
    "projectName": "extrait de parfum gaharu",
    "pic": "Panca",
    "client": "Masheru 130826",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/21/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-64",
    "no": "64",
    "projectName": "extrait de parfum kasturi",
    "pic": "Panca",
    "client": "Masheru 130827",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/21/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-65",
    "no": "65",
    "projectName": "extrait de parfum ambergis",
    "pic": "Panca",
    "client": "Masheru 130828",
    "status": "Terkirim",
    "tglNpfMasuk": "8/18/2026",
    "tglSelesai": "8/21/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-66",
    "no": "66",
    "projectName": "Sunscreen",
    "pic": "Panca",
    "client": "yuri karmila",
    "status": "Terkirim",
    "tglNpfMasuk": "8/26/2026",
    "tglSelesai": "8/31/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-67",
    "no": "67",
    "projectName": "Facial wash",
    "pic": "Panca",
    "client": "yuri karmila",
    "status": "Terkirim",
    "tglNpfMasuk": "8/26/2026",
    "tglSelesai": "8/26/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-68",
    "no": "68",
    "projectName": "moisturizer brightening",
    "pic": "Panca",
    "client": "yuri karmila",
    "status": "Terkirim",
    "tglNpfMasuk": "8/26/2026",
    "tglSelesai": "8/26/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-69",
    "no": "69",
    "projectName": "serum",
    "pic": "Panca",
    "client": "yuri karmila",
    "status": "Terkirim",
    "tglNpfMasuk": "8/26/2026",
    "tglSelesai": "8/27/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  },
  {
    "id": "PROJ-RND-70",
    "no": "70",
    "projectName": "Extrait Baccarat Rouge 540 style (Card Rougea)",
    "pic": "Panca",
    "client": "Agusma",
    "status": "Terkirim",
    "tglNpfMasuk": "8/26/2026",
    "tglSelesai": "8/31/2026",
    "tglPengiriman": "",
    "totalPengerjaan": "-",
    "folderFormula": "-",
    "notes": ""
  }
];
