"use client";

import { FormEvent, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BarChart3, DollarSign, Eye, MousePointerClick, Plus, Users } from "lucide-react";
import { DnaButton, DnaDrawer, DnaInput, DnaKpiGrid, DnaPageContainer, DnaPageHeader, DnaTextarea } from "@/components/dna";
import { extractApiError } from "@/lib/api";
import { useAuth } from "@/hooks/useAuth";
import { MarketingBrand, useMarketingBrands, useMarketingReports, useUpsertChannelMetric } from "@/hooks/useCanonicalMarketing";

const number = (value: unknown) => Number(value || 0);
const format = (value: number) => new Intl.NumberFormat("id-ID", { notation: value > 999999 ? "compact" : "standard", maximumFractionDigits: 1 }).format(value);
const money = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);

export function MarketingReporting() {
  const { hasRole } = useAuth(); const brands = useMarketingBrands(); const [brandId,setBrandId]=useState(""); const [channel,setChannel]=useState(""); const [open,setOpen]=useState(false); const [message,setMessage]=useState<string|null>(null);
  const reports=useMarketingReports({brandId:brandId||undefined,channel:channel||undefined}); const save=useUpsertChannelMetric();
  const metrics=(reports.data?.data??[]).flatMap((period:any)=>period.channelMetrics??[]);
  const total=useMemo(()=>metrics.reduce((a:any,m:any)=>({reach:a.reach+number(m.reach),views:a.views+number(m.views),leads:a.leads+number(m.leads),spend:a.spend+number(m.spend),revenue:a.revenue+number(m.revenue)}),{reach:0,views:0,leads:0,spend:0,revenue:0}),[metrics]);
  const canWrite=hasRole("SUPER_ADMIN","MARKETING","DIGIMAR");
  return <DnaPageContainer className="mx-auto max-w-[1500px] space-y-5 p-4 sm:p-6 lg:p-8"><DnaPageHeader title="MARKETING REPORTING" subtitle="Metrik terverifikasi per brand, channel, dan periode" backLink={{href:"/marketing/social-tracker",label:"Kembali ke Social Planner"}} actions={canWrite?<DnaButton variant="primary" icon={<Plus/>} onClick={()=>setOpen(true)}>Input metrik</DnaButton>:undefined}/>
    {message&&<div aria-live="polite" className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}
    <DnaKpiGrid items={[{label:"TOTAL REACH",value:format(total.reach),subtext:"Akumulasi hasil filter",icon:Users,variant:"blue"},{label:"VIEWS",value:format(total.views),subtext:"Raw fact",icon:Eye,variant:"purple"},{label:"LEADS",value:format(total.leads),subtext:"Attribution tercatat",icon:MousePointerClick,variant:"amber"},{label:"ROAS",value:total.spend?`${(total.revenue/total.spend).toFixed(2)}×`:"—",subtext:`Spend ${money(total.spend)}`,icon:DollarSign,variant:"emerald"}]}/>
    <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-2"><select aria-label="Filter brand" value={brandId} onChange={e=>setBrandId(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option value="">Semua brand</option>{brands.data?.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><DnaInput aria-label="Filter channel" value={channel} onChange={e=>setChannel(e.target.value)} placeholder="Channel, contoh Instagram"/></div>
      {reports.isLoading?<div className="space-y-2 p-4">{Array.from({length:5}).map((_,i)=><div key={i} className="h-14 animate-pulse rounded bg-slate-100"/>)}</div>:reports.isError?<State text="Reporting gagal dimuat." action={<DnaButton variant="outline" onClick={()=>reports.refetch()}>Coba lagi</DnaButton>}/>:metrics.length===0?<State text="Belum ada metrik terverifikasi untuk filter ini." action={canWrite?<DnaButton variant="primary" onClick={()=>setOpen(true)}>Input metrik</DnaButton>:undefined}/>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr>{["Channel","Periode","Source","Reach","Views","Leads","CPL","ROAS"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{metrics.map((m:any)=><tr key={m.id}><td className="px-4 py-3 font-bold">{m.channel}</td><td className="px-4 py-3">{new Date(m.periodStart).toLocaleDateString("id-ID")} – {new Date(m.periodEnd).toLocaleDateString("id-ID")}</td><td className="px-4 py-3">{m.source}</td><td className="px-4 py-3 tabular-nums">{format(number(m.reach))}</td><td className="px-4 py-3 tabular-nums">{format(number(m.views))}</td><td className="px-4 py-3 tabular-nums">{format(number(m.leads))}</td><td className="px-4 py-3">{m.cpl==null?"—":money(number(m.cpl))}</td><td className="px-4 py-3">{m.roas==null?"—":`${number(m.roas).toFixed(2)}×`}</td></tr>)}</tbody></table></div>}</section>
    <MetricModal open={open} onClose={()=>setOpen(false)} brands={brands.data??[]} saving={save.isPending} onSave={async data=>{try{await save.mutateAsync(data);setOpen(false);setMessage("Metrik berhasil disimpan dan agregat dihitung ulang oleh server.")}catch(e){setMessage(extractApiError(e).message)}}}/>
  </DnaPageContainer>
}
function State({text,action}:{text:string;action?:React.ReactNode}){return <div className="grid place-items-center gap-3 p-12 text-center"><BarChart3 className="h-9 w-9 text-slate-300"/><p className="text-sm text-slate-500">{text}</p>{action}</div>}
function MetricModal({open,onClose,brands,saving,onSave}:{open:boolean;onClose:()=>void;brands:MarketingBrand[];saving:boolean;onSave:(data:Record<string,unknown>)=>Promise<void>}){const today=new Date().toISOString().slice(0,10);const [f,setF]=useState<any>({brandId:"",channel:"Instagram",periodStart:today,periodEnd:today,followersStart:0,followersEnd:0,reach:0,views:0,impressions:0,likes:0,comments:0,shares:0,saves:0,clicks:0,leads:0,sampleRequests:0,deals:0,spend:0,revenue:0,source:"MANUAL"});const set=(k:string)=>(e:any)=>setF((x:any)=>({...x,[k]:e.target.type==="number"?Number(e.target.value):e.target.value}));const submit=(e:FormEvent)=>{e.preventDefault();return onSave({...f,periodStart:new Date(`${f.periodStart}T00:00:00+07:00`).toISOString(),periodEnd:new Date(`${f.periodEnd}T23:59:59+07:00`).toISOString()})};return <DnaDrawer isOpen={open} onClose={onClose} title="Input metrik channel" subtitle="Masukkan raw facts; CPL, engagement, growth, dan ROAS dihitung server" size="3xl" footer={<><DnaButton variant="outline" onClick={onClose}>Batal</DnaButton><DnaButton variant="primary" loading={saving} onClick={()=>document.getElementById("metric-form")?.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}))}>Simpan metrik</DnaButton></>}><form id="metric-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-bold">Brand<select required value={f.brandId} onChange={set("brandId")} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3"><option value="">Pilih brand</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><DnaInput required label="Channel" value={f.channel} onChange={set("channel")}/><DnaInput required type="date" label="Awal periode" value={f.periodStart} onChange={set("periodStart")}/><DnaInput required type="date" label="Akhir periode" value={f.periodEnd} onChange={set("periodEnd")}/>{["followersStart","followersEnd","reach","views","impressions","likes","comments","shares","saves","clicks","leads","sampleRequests","deals","spend","revenue"].map(k=><DnaInput key={k} type="number" min={0} label={k.replace(/([A-Z])/g," $1")} value={f[k]} onChange={set(k)}/>)}</form></DnaDrawer>}
