const fs = require('fs');
const path = require('path');

const file = path.resolve(__dirname, '../../docs/legacy-erp/contracts/10_TRACEABILITY_MATRIX.yaml');
let text = fs.readFileSync(file, 'utf8');

// Mechanical aliases from obsolete catalog vocabulary to canonical schema/API names.
const replacements = [
  ['CustomerPayment', 'SalesPayment'],
  ['VendorInvoice', 'PurchaseInvoice'],
  ['SampleFee', 'SalesSamplePayment'],
  ['SalesOrderChecklistItem', 'ChecklistProgress'],
  ['CreditNote', 'SalesReturn'],
  ['InternalTransfer', 'StockMovement'],
  ['JobOrderCosting', 'PurchaseInvoiceDetail'],
  ['BatchRecordLine', 'ProductionMixingItem'],
  ['BatchRecordMaterial', 'ProductionMixingItem'],
  ['BatchRecordFilling', 'ProductionFilling'],
  ['/api/v1/master/suppliers', '/api/v1/suppliers'],
  ['/api/v1/master/customers', '/api/v1/customers'],
  ['/api/v1/master/coa', '/api/v1/coa'],
  ['/api/v1/master/search', '/api/v1/search'],
  ['/api/v1/sales/invoices', '/api/v1/sales/sales-invoices'],
  ['/api/v1/sales/payments/pph23', '/api/v1/sales/sales-payments'],
  ['/api/v1/sales/payments', '/api/v1/sales/sales-payments'],
  ['/api/v1/sales/orders', '/api/v1/sales/sales-orders'],
  ['/api/v1/reports/ap-aging/summary', '/api/v1/reports/ap-aging'],
  ['/api/v1/reports/pl', '/api/v1/reports/profit-loss'],
  ['/api/v1/finance/cash-banks/in', '/api/v1/finance/cash-banks'],
  ['/api/v1/finance/cash-banks/out', '/api/v1/finance/cash-banks'],
  ['/api/v1/warehouse/stock', '/api/v1/reports/stock'],
  ['/master/suppliers', '/suppliers'],
  ['/master/coa', '/coa'],
  ['/sales/invoices', '/sales/sales-invoices'],
  ['/sales/payments', '/sales/sales-payments'],
  ['/sales/orders', '/sales/sales-orders'],
  ['/sales/credit-notes', '/sales/sales-returns'],
  ['/sales/orders/add-cart', '/sales/sales-orders'],
  ['/warehouse/transfers', '/warehouse/goods-transfer'],
  ['/purchase/orders/{id}/post', '/purchase/orders/{id}/approve'],
  ['/production/batch-records/{id}/stage', '/production/batch-records/{id}/process'],
  ['/production/mixing/actual', '/production/production-mixing'],
  ['/production/mixing/scan', '/production/production-mixing'],
  ['/production/filling/start', '/production/production-filling'],
  ['/production/filling', '/production/production-filling'],
  ['/production/packaging/start', '/production/production-packaging'],
  ['/production/packaging/post', '/production/production-packaging'],
  ['/production/packaging', '/production/production-packaging'],
  ['/rnd/formulations/{id}/grams', '/rnd/formulations/{id}'],
  ['/rnd/formulations/{id}/hpp', '/rnd/formulations/{id}'],
  ['/rnd/formulations/{id}/revise', '/rnd/formulations/{id}/clone'],
  ['/warehouse/movements', '/warehouse/stock-movements'],
  ['/warehouse/stock-opnames/{id}/approve', '/warehouse/stock-opname/{id}/approve'],
  ['/warehouse/stock-opnames/{id}/post', '/warehouse/stock-opname/{id}/approve'],
  ['/warehouse/dead-stock', '/reports/stock'],
  ['/warehouse/{id}/stock', '/goods/{id}/stock'],
  ['/production/reconcile', '/production/batch-records/{id}/process'],
  ['/finance/journal/manual', '/finance/journal-entries'],
  ['/reports/sales', '/reports/sales-summary'],
  ['/reports/pl', '/reports/profit-loss'],
  ['/production/kpi/fty', '/dashboards/production'],
  ['/production/kpi/copq', '/dashboards/qc'],
  ['/production/kpi/oee', '/dashboards/production'],
  ['/sales/kpi/cpl', '/dashboards/busdev'],
  ['/sales/kpi/conversion', '/dashboards/busdev'],
  ['/sales/kpi/retention', '/dashboards/busdev'],
  ['/sales/kpi/otd', '/dashboards/busdev'],
  ['/finance/kpi/collection', '/dashboards/finance'],
  ['/finance/kpi/expense-ratio', '/dashboards/finance'],
  ['/finance/kpi/net-margin', '/dashboards/finance'],
  ['/reports/ar-aging/distribution', '/reports/ar-aging'],
  ['/master/suppliers/{id}/block', '/suppliers/{id}'],
  ['/finance/numbers/next', '/system/sequence/next'],
  ['/master/coa/{id}', '/coa/{id}'],
  ['PATCH /production/batch-records/{id}/process', 'POST /production/batch-records/{id}/process'],
  ['PATCH /production/production-filling', 'POST /production/production-filling'],
  ['PATCH /production/production-packaging', 'POST /production/production-packaging'],
  ['POST /suppliers/{id}/block', 'PATCH /suppliers/{id}'],
  ['POST /hr/reimburse', 'POST /finance/fund-requests'],
  ['POST /production/defects', 'POST /production/qc-inspections'],
  ['POST /api/v1/purchase/goods-receipts/report', 'POST /api/v1/reports/goods-receipts'],
];

for (const [from, to] of replacements) text = text.split(from).join(to);

// Repair names that were historically generated by a broad Approval/Period alias.
const generatedNameRepairs = [
  ['SalesSampleStatusTransition', 'SalesSampleApproval'],
  ['SalesOrderStatusTransition', 'SalesOrderApproval'],
  ['SalesReturnStatusTransition', 'SalesReturnApproval'],
  ['PurchaseRequestStatusTransition', 'PurchaseRequestApproval'],
  ['PurchaseOrderStatusTransition', 'PurchaseOrderApproval'],
  ['PurchaseReturnStatusTransition', 'PurchaseReturnApproval'],
  ['PO: StatusTransition Tanda Tangan Digital', 'PO: Approval Tanda Tangan Digital'],
  ['SLA Timer: Pending StatusTransition', 'SLA Timer: Pending Approval'],
  ['Universal StatusTransition', 'Universal Approval'],
  ['StatusTransition Center', 'Approval Center'],
  ['StatusTransition Detail', 'Approval Detail'],
  ['StatusTransition Queue', 'Approval Queue'],
  ['Returns StatusTransition', 'Returns Approval'],
  ['Return StatusTransition', 'Return Approval'],
  ['Checklist StatusTransition', 'Checklist Approval'],
  ['StatusTransition sub-delegation', 'Approval sub-delegation'],
  ['BatchRecord Categorization', 'Defect Categorization'],
  ['JournalEntry Lock', 'Period Lock'],
  ['JournalEntry Management', 'Period Management'],
  ['Hard Lock JournalEntry', 'Hard Lock Period'],
  ['lockJournalEntry', 'lockPeriod'],
  ['/reports/sales-summary-summary', '/reports/sales-summary'],
  ['/finance/journal-entries-entries', '/finance/journal-entries'],
  ['/sales/sales-orders/add-cart', '/sales/sales-orders'],
];
for (const [from, to] of generatedNameRepairs) text = text.split(from).join(to);
text = text.replace(/\/reports\/sales-summary(?:-summary)+/g, '/reports/sales-summary');
text = text.replace(/\/finance\/journal-entries(?:-entries)+/g, '/finance/journal-entries');

// Cart state is Redis-transient and therefore deliberately has no Prisma entity.
text = text.replace(/ents: \[CartSession\]/g, 'ents: []');
// Deferred tax screen has no runtime screen reference.
text = text.replace(/screens: \[\[\]\]/g, 'screens: []');
text = text.replace(/(id: BUS-RULE-073[^\n]*?)apis: \['POST \/hr\/payroll'\]/, '$1apis: []');

fs.writeFileSync(file, text);
console.log(`Rewrote canonical traceability aliases in ${file}`);
