-- Drop duplicate redundant non-unique indexes on slug columns
-- (slug already has unique constraint and index generated by @unique)
DROP INDEX IF EXISTS "articles_slug_idx";
DROP INDEX IF EXISTS "website_products_slug_idx";
