"use client";

import { FormEvent, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { BarChart3, CalendarDays, FileText, LayoutGrid, List, Plus, RefreshCw, Search, Settings2 } from "lucide-react";
import { DnaButton, DnaDrawer, DnaInput, DnaKpiGrid, DnaPageContainer, DnaPageHeader, DnaPagination, DnaTabNav, DnaTextarea } from "@/components/dna";
import { extractApiError } from "@/lib/api";
import { MarketingBrand, MarketingMember, SocialPost, SocialStatus, useCanonicalSocialPosts, useCreateCanonicalSocialPost, useMarketingBrands, useMarketingMembers, useSocialStatusMutation } from "@/hooks/useCanonicalMarketing";

const SOCIAL_LABEL: Record<SocialStatus, string> = { IDEA: "Ide", DRAFT: "Draft", SCRIPTING: "Scripting", PRODUCTION: "Produksi", IN_REVIEW: "Review", REVISION: "Revisi", APPROVED: "Disetujui", SCHEDULED: "Terjadwal", PUBLISHED: "Terbit", ARCHIVED: "Arsip" };
const FLOW: Partial<Record<SocialStatus, SocialStatus[]>> = { IDEA: ["DRAFT", "ARCHIVED"], DRAFT: ["SCRIPTING", "ARCHIVED"], SCRIPTING: ["PRODUCTION", "ARCHIVED"], PRODUCTION: ["IN_REVIEW", "ARCHIVED"], IN_REVIEW: ["APPROVED", "REVISION", "ARCHIVED"], REVISION: ["PRODUCTION", "ARCHIVED"], APPROVED: ["SCHEDULED", "ARCHIVED"], SCHEDULED: ["PUBLISHED", "ARCHIVED"], PUBLISHED: ["ARCHIVED"] };
const ALL_STATUS = Object.keys(SOCIAL_LABEL) as SocialStatus[];
const statusStyle = (status: SocialStatus) => status === "PUBLISHED" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : status === "REVISION" || status === "ARCHIVED" ? "border-rose-200 bg-rose-50 text-rose-700" : status === "SCHEDULED" || status === "APPROVED" ? "border-violet-200 bg-violet-50 text-violet-700" : status === "IN_REVIEW" ? "border-amber-200 bg-amber-50 text-amber-800" : "border-blue-200 bg-blue-50 text-blue-700";
function prettyDate(value?: string) { return value ? new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—"; }

export function SocialPlanner() {
  const router = useRouter(); const pathname = usePathname(); const sp = useSearchParams();
  const view = sp.get("view") ?? "table"; const page = Number(sp.get("page") || 1); const limit = Number(sp.get("limit") || 25);
  const [search, setSearch] = useState(sp.get("q") ?? ""); const [selected, setSelected] = useState<SocialPost | null>(null); const [createOpen, setCreateOpen] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const filters = { page, limit, search: sp.get("q") || undefined, status: sp.get("status") || undefined, platform: sp.get("platform") || undefined, pillar: sp.get("pillar") || undefined };
  const posts = useCanonicalSocialPosts(filters); const brands = useMarketingBrands(); const members = useMarketingMembers(); const createPost = useCreateCanonicalSocialPost(); const movePost = useSocialStatusMutation();
  function url(changes: Record<string, string | null>) { const next = new URLSearchParams(sp.toString()); Object.entries(changes).forEach(([k,v]) => v && v !== "all" ? next.set(k,v) : next.delete(k)); router.replace(`${pathname}${next.size ? `?${next}` : ""}`, { scroll: false }); }
  const rows = posts.data?.data ?? [];
  const counts = useMemo(() => ({ total: posts.data?.total ?? 0, idea: rows.filter(x => x.status === "IDEA").length, scheduled: rows.filter(x => x.status === "SCHEDULED").length, published: rows.filter(x => x.status === "PUBLISHED").length }), [rows, posts.data?.total]);
  async function transition(post: SocialPost, status: SocialStatus) { try { const updated = await movePost.mutateAsync({ post, status }); setSelected(updated); setMessage(`Status “${post.title}” menjadi ${SOCIAL_LABEL[status]}.`); } catch (error) { const parsed = extractApiError(error); setMessage(parsed.status === 409 ? "Data atau prasyarat workflow berubah. Muat ulang lalu periksa brand, PIC, jadwal, dan bukti publikasi." : parsed.message); if (parsed.status === 409) posts.refetch(); } }

  return <DnaPageContainer className="mx-auto max-w-[1500px] space-y-5 p-4 sm:p-6 lg:p-8">
    <DnaPageHeader title="SOCIAL MEDIA PLANNER" subtitle="Kalender konten, approval, dan publikasi lintas platform" breadcrumbs={[{ label: "Marketing", href: "/marketing/dashboard" }, { label: "Social Media" }]} actions={<div className="flex gap-2"><DnaButton variant="outline" icon={<RefreshCw/>} onClick={() => posts.refetch()}>Refresh</DnaButton><DnaButton variant="primary" icon={<Plus/>} onClick={() => setCreateOpen(true)}>Tambah konten</DnaButton></div>} />
    {message && <div aria-live="polite" role="status" className="flex min-h-11 items-center justify-between rounded-xl border border-blue-200 bg-blue-50 px-4 text-sm text-blue-800"><span>{message}</span><button className="min-h-11 px-3 font-bold" onClick={() => setMessage(null)}>Tutup</button></div>}
    <DnaKpiGrid items={[{label:"TOTAL KONTEN",value:counts.total,subtext:"Sesuai filter aktif",icon:FileText,variant:"blue"},{label:"IDE BARU",value:counts.idea,subtext:"Menunggu pengembangan",icon:Plus,variant:"amber"},{label:"TERJADWAL",value:counts.scheduled,subtext:"Siap dipublikasikan",icon:CalendarDays,variant:"purple"},{label:"TERBIT",value:counts.published,subtext:"Pada halaman ini",icon:BarChart3,variant:"emerald"}]} />
    <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><DnaTabNav activeTab={view} onChange={(v) => url({ view: v, page: "1" })} tabs={[{id:"table",label:"Tabel",icon:List},{id:"board",label:"Kanban",icon:LayoutGrid},{id:"calendar",label:"Kalender",icon:CalendarDays}]} /><div className="flex gap-2"><Link href="/marketing/social-tracker/reporting" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold uppercase tracking-wider text-slate-700 hover:bg-slate-50"><BarChart3 className="h-4 w-4"/>Reporting</Link><Link href="/marketing/social-tracker/integrations" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold uppercase tracking-wider text-slate-700 hover:bg-slate-50"><Settings2 className="h-4 w-4"/>Integrasi</Link></div></div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-2 lg:grid-cols-4"><DnaInput aria-label="Cari konten" icon={<Search/>} value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === "Enter" && url({ q: search, page: "1" })} placeholder="Cari judul atau caption..."/><Select label="Semua platform" value={sp.get("platform") ?? "all"} onChange={(v) => url({platform:v,page:"1"})} options={["instagram","facebook","tiktok","threads","youtube","linkedin"]}/><Select label="Semua status" value={sp.get("status") ?? "all"} onChange={(v) => url({status:v,page:"1"})} options={ALL_STATUS}/><DnaButton variant="outline" icon={<RefreshCw/>} onClick={() => { setSearch(""); router.replace(pathname); }}>Reset filter</DnaButton></div>
      {posts.isLoading ? <div className="space-y-2 p-4">{Array.from({length:6}).map((_,i)=><div key={i} className="h-16 animate-pulse rounded-lg bg-slate-100"/>)}</div> : posts.isError ? <State title="Konten gagal dimuat" text="Tidak ada sample fallback. Periksa API lalu coba kembali." action={<DnaButton variant="outline" onClick={() => posts.refetch()}>Coba lagi</DnaButton>}/> : rows.length === 0 ? <State title="Belum ada konten" text="Mulai dari ide baru untuk kalender konten ini." action={<DnaButton variant="primary" icon={<Plus/>} onClick={() => setCreateOpen(true)}>Tambah konten</DnaButton>}/> : view === "board" ? <Board rows={rows} onOpen={setSelected}/> : view === "calendar" ? <Calendar rows={rows} onOpen={setSelected}/> : <SocialTable rows={rows} onOpen={setSelected}/>} 
      <DnaPagination currentPage={page} totalPages={Math.max(1,Math.ceil((posts.data?.total ?? 0)/limit))} totalEntries={posts.data?.total ?? 0} pageSize={limit} onPageChange={(p)=>url({page:String(p)})} onPageSizeChange={(n)=>url({limit:String(n),page:"1"})}/>
    </section>
    <CreateSocialModal open={createOpen} onClose={()=>setCreateOpen(false)} brands={brands.data ?? []} members={members.data ?? []} saving={createPost.isPending} onSave={async(data)=>{try{await createPost.mutateAsync(data);setCreateOpen(false);setMessage("Konten baru tersimpan sebagai Ide.");}catch(e){setMessage(extractApiError(e).message)}}}/>
    <DnaDrawer isOpen={!!selected} onClose={()=>setSelected(null)} title={selected?.title ?? "Detail konten"} subtitle={selected ? `${selected.platform} · ${selected.contentType}` : undefined} badge={selected && <Badge status={selected.status}/>} size="2xl" footer={selected && <div className="flex flex-wrap justify-end gap-2">{(FLOW[selected.status]??[]).map(next=><DnaButton key={next} variant={next==="ARCHIVED"?"danger":"primary"} loading={movePost.isPending} onClick={()=>transition(selected,next)}>Ke {SOCIAL_LABEL[next]}</DnaButton>)}</div>}>
      {selected && <div className="space-y-5"><div className="grid grid-cols-2 gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm"><Info label="Brand" value={selected.brand?.name ?? "—"}/><Info label="PIC" value={selected.assignee?.fullName ?? "—"}/><Info label="Jadwal" value={prettyDate(selected.scheduledDate)}/><Info label="Versi" value={String(selected.version)}/></div><div><h3 className="mb-2 text-sm font-bold">Creative brief</h3><p className="whitespace-pre-wrap rounded-xl border border-slate-200 p-4 leading-6 text-slate-600">{selected.brief || selected.caption || "Belum ada brief."}</p></div><div><h3 className="mb-2 text-sm font-bold">Checklist</h3>{selected.checklist?.length ? selected.checklist.map(item=><div key={item.id} className="flex min-h-11 items-center gap-3 border-b border-slate-100"><CheckMark done={item.done}/><span className={item.done?"text-slate-400 line-through":"text-slate-700"}>{item.text}</span></div>) : <p className="text-sm text-slate-400">Belum ada checklist.</p>}</div></div>}
    </DnaDrawer>
  </DnaPageContainer>;
}

function Badge({status}:{status:SocialStatus}){return <span className={`rounded-full border px-2.5 py-1 text-[11px] font-bold ${statusStyle(status)}`}>{SOCIAL_LABEL[status]}</span>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-medium outline-none focus:border-blue-500"><option value="all">{label}</option>{options.map(x=><option key={x} value={x}>{SOCIAL_LABEL[x as SocialStatus]??x}</option>)}</select>}
function State({title,text,action}:{title:string;text:string;action:React.ReactNode}){return <div className="grid place-items-center gap-3 p-14 text-center"><FileText className="h-9 w-9 text-slate-300"/><div><p className="font-bold text-slate-900">{title}</p><p className="text-sm text-slate-500">{text}</p></div>{action}</div>}
function SocialTable({rows,onOpen}:{rows:SocialPost[];onOpen:(p:SocialPost)=>void}){return <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr>{["Konten","Brand","Platform","PIC","Status","Jadwal"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(p=><tr key={p.id} tabIndex={0} onClick={()=>onOpen(p)} onKeyDown={e=>e.key==="Enter"&&onOpen(p)} className="cursor-pointer hover:bg-blue-50/40 focus:bg-blue-50 focus:outline-none"><td className="px-4 py-3"><p className="font-bold text-slate-900">{p.title}</p><p className="text-xs text-slate-400">{p.pillar||p.contentType}</p></td><td className="px-4 py-3">{p.brand?.name??"—"}</td><td className="px-4 py-3 capitalize">{p.platform}</td><td className="px-4 py-3">{p.assignee?.fullName??"—"}</td><td className="px-4 py-3"><Badge status={p.status}/></td><td className="px-4 py-3">{prettyDate(p.scheduledDate)}</td></tr>)}</tbody></table></div>}
function Board({rows,onOpen}:{rows:SocialPost[];onOpen:(p:SocialPost)=>void}){const groups=ALL_STATUS.filter(s=>rows.some(p=>p.status===s));return <div className="flex gap-3 overflow-x-auto p-4">{groups.map(status=><section key={status} className="w-72 shrink-0 rounded-xl bg-slate-50 p-3"><div className="mb-3 flex items-center justify-between"><Badge status={status}/><span className="text-xs font-bold text-slate-400">{rows.filter(p=>p.status===status).length}</span></div><div className="space-y-2">{rows.filter(p=>p.status===status).map(p=><button key={p.id} onClick={()=>onOpen(p)} className="min-h-20 w-full rounded-xl border border-slate-200 bg-white p-3 text-left shadow-sm hover:border-blue-300"><p className="font-bold text-slate-900">{p.title}</p><p className="mt-2 text-xs capitalize text-slate-400">{p.platform} · {p.assignee?.fullName??"Belum ada PIC"}</p></button>)}</div></section>)}</div>}
function Calendar({rows,onOpen}:{rows:SocialPost[];onOpen:(p:SocialPost)=>void}){const groups=Object.entries(rows.reduce<Record<string,SocialPost[]>>((a,p)=>{const d=(p.scheduledDate||p.createdAt).slice(0,10);(a[d]??=[]).push(p);return a},{})).sort(([a],[b])=>a.localeCompare(b));return <div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{groups.map(([date,items])=><section key={date} className="rounded-xl border border-slate-200 p-4"><h3 className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-500">{prettyDate(date)}</h3>{items.map(p=><button key={p.id} onClick={()=>onOpen(p)} className="mb-2 block min-h-11 w-full rounded-lg bg-slate-50 px-3 text-left text-sm font-semibold hover:bg-blue-50">{p.title}</button>)}</section>)}</div>}
function CheckMark({done}:{done:boolean}){return <span aria-label={done?"Selesai":"Belum selesai"} className={`grid h-5 w-5 place-items-center rounded-full border text-xs ${done?"border-emerald-500 bg-emerald-500 text-white":"border-slate-300"}`}>{done?"✓":""}</span>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 font-semibold text-slate-800">{value}</p></div>}
function CreateSocialModal({open,onClose,brands,members,saving,onSave}:{open:boolean;onClose:()=>void;brands:MarketingBrand[];members:MarketingMember[];saving:boolean;onSave:(data:Partial<SocialPost>)=>Promise<void>}){const [form,setForm]=useState({title:"",platform:"instagram",contentType:"single_post",brandId:"",assigneeId:"",pillar:"",brief:""});const set=(k:string)=>(e:any)=>setForm(x=>({...x,[k]:e.target.value}));const submit=async(e:FormEvent)=>{e.preventDefault();await onSave({...form,brandId:form.brandId||undefined,assigneeId:form.assigneeId||undefined})};return <DnaDrawer isOpen={open} onClose={onClose} title="Tambah konten" subtitle="Konten baru selalu dimulai dari tahap Ide" footer={<><DnaButton variant="outline" onClick={onClose}>Batal</DnaButton><DnaButton variant="primary" loading={saving} onClick={()=>document.getElementById("social-create-form")?.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}))}>Simpan ide</DnaButton></>}><form id="social-create-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><DnaInput required label="Judul konten" value={form.title} onChange={set("title")}/><FormSelect label="Platform" value={form.platform} onChange={set("platform")} options={["instagram","facebook","tiktok","threads","youtube","linkedin"]}/><FormSelect label="Format" value={form.contentType} onChange={set("contentType")} options={["single_post","carousel","reel","story","video","live"]}/><FormSelect label="Brand" value={form.brandId} onChange={set("brandId")} options={brands.map(x=>({value:x.id,label:x.name}))}/><FormSelect label="PIC" value={form.assigneeId} onChange={set("assigneeId")} options={members.map(x=>({value:x.id,label:x.fullName}))}/><DnaInput label="Content pillar" value={form.pillar} onChange={set("pillar")}/><div className="sm:col-span-2"><DnaTextarea label="Creative brief" value={form.brief} onChange={set("brief")} rows={5}/></div></form></DnaDrawer>}
function FormSelect({label,value,onChange,options}:{label:string;value:string;onChange:(e:any)=>void;options:Array<string|{value:string;label:string}>}){return <label className="text-xs font-bold text-slate-700">{label}<select value={value} onChange={onChange} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-medium"><option value="">Pilih {label.toLowerCase()}</option>{options.map(raw=>{const x=typeof raw==="string"?{value:raw,label:raw}:raw;return <option key={x.value} value={x.value}>{x.label}</option>})}</select></label>}
