"use client";

import { FormEvent, useState } from "react";
import { Cable, CheckCircle2, Clock3, Plus, RefreshCw, ShieldCheck } from "lucide-react";
import { DnaButton, DnaDrawer, DnaKpiGrid, DnaPageContainer, DnaPageHeader, DnaInput } from "@/components/dna";
import { extractApiError } from "@/lib/api";
import { useAuth } from "@/hooks/useAuth";
import { MarketingBrand, useConfigureIntegration, useMarketingBrands, useMarketingIntegrations, useTriggerIntegrationSync } from "@/hooks/useCanonicalMarketing";

export function MarketingIntegrations(){const {hasRole}=useAuth();const brands=useMarketingBrands();const [brandId,setBrandId]=useState("");const [open,setOpen]=useState(false);const [message,setMessage]=useState<string|null>(null);const data=useMarketingIntegrations(brandId||undefined);const configure=useConfigureIntegration();const sync=useTriggerIntegrationSync();const rows=data.data??[];const canConfigure=hasRole("SUPER_ADMIN","MARKETING");const canSync=hasRole("SUPER_ADMIN","MARKETING","DIGIMAR");return <DnaPageContainer className="mx-auto max-w-[1400px] space-y-5 p-4 sm:p-6 lg:p-8"><DnaPageHeader title="SOCIAL INTEGRATIONS" subtitle="Koneksi provider, freshness, dan immutable sync history" backLink={{href:"/marketing/social-tracker",label:"Kembali ke Social Planner"}} actions={canConfigure?<DnaButton variant="primary" icon={<Plus/>} onClick={()=>setOpen(true)}>Konfigurasi</DnaButton>:undefined}/>
{message&&<div aria-live="polite" className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}<DnaKpiGrid items={[{label:"TOTAL KONEKSI",value:rows.length,subtext:"Provider terdaftar",icon:Cable,variant:"blue"},{label:"CONNECTED",value:rows.filter(x=>x.status==="CONNECTED").length,subtext:"Siap sinkronisasi",icon:CheckCircle2,variant:"emerald"},{label:"PERLU PERHATIAN",value:rows.filter(x=>!["CONNECTED","DISCONNECTED"].includes(x.status)).length,subtext:"Error atau token expired",icon:ShieldCheck,variant:"rose"},{label:"SYNC TERBARU",value:rows.some(x=>x.lastSyncAt)?"Tersedia":"—",subtext:"Lihat detail koneksi",icon:Clock3,variant:"amber"}]}/>
<section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-4"><select aria-label="Filter brand" value={brandId} onChange={e=>setBrandId(e.target.value)} className="h-11 w-full max-w-sm rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option value="">Semua brand</option>{brands.data?.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>{data.isLoading?<div className="space-y-3 p-4">{Array.from({length:4}).map((_,i)=><div key={i} className="h-24 animate-pulse rounded-xl bg-slate-100"/>)}</div>:data.isError?<Empty text="Koneksi gagal dimuat."/>:rows.length===0?<Empty text="Belum ada koneksi provider. Secret tidak pernah ditampilkan kembali."/>:<div className="grid gap-4 p-4 md:grid-cols-2">{rows.map(row=><article key={row.id} className="rounded-xl border border-slate-200 p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{row.brand?.name??"Brand"}</p><h2 className="mt-1 text-lg font-black text-slate-900">{row.provider}</h2></div><span className={`rounded-full border px-2.5 py-1 text-[11px] font-bold ${row.status==="CONNECTED"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-slate-200 bg-slate-50 text-slate-600"}`}>{row.status}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Info label="Last sync" value={row.lastSyncAt?new Date(row.lastSyncAt).toLocaleString("id-ID"):"Belum pernah"}/><Info label="Scopes" value={row.scopes?.join(", ")||"—"}/></dl>{canSync&&<DnaButton className="mt-4 w-full" variant="outline" icon={<RefreshCw/>} loading={sync.isPending} onClick={async()=>{try{await sync.mutateAsync(row.id);setMessage(`Sync ${row.provider} masuk antrean.`)}catch(e){setMessage(extractApiError(e).message)}}}>Queue sync</DnaButton>}</article>)}</div>}</section>
<ConnectionModal open={open} onClose={()=>setOpen(false)} brands={brands.data??[]} saving={configure.isPending} onSave={async payload=>{try{await configure.mutateAsync(payload);setOpen(false);setMessage("Konfigurasi tersimpan. Secret telah dienkripsi server-side.")}catch(e){setMessage(extractApiError(e).message)}}}/></DnaPageContainer>}
function Empty({text}:{text:string}){return <div className="grid place-items-center gap-3 p-12 text-center"><Cable className="h-9 w-9 text-slate-300"/><p className="text-sm text-slate-500">{text}</p></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-[10px] font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 break-words font-semibold text-slate-700">{value}</dd></div>}
function ConnectionModal({open,onClose,brands,saving,onSave}:{open:boolean;onClose:()=>void;brands:MarketingBrand[];saving:boolean;onSave:(data:{brandId:string;provider:string;secret?:string;config:Record<string,unknown>;scopes:string[]})=>Promise<void>}){const [f,setF]=useState({brandId:"",provider:"META",secret:"",externalId:"",scopes:"read_insights"});const set=(k:string)=>(e:any)=>setF(x=>({...x,[k]:e.target.value}));const submit=(e:FormEvent)=>{e.preventDefault();return onSave({brandId:f.brandId,provider:f.provider,secret:f.secret||undefined,config:{externalId:f.externalId},scopes:f.scopes.split(",").map(x=>x.trim()).filter(Boolean)})};return <DnaDrawer isOpen={open} onClose={onClose} title="Konfigurasi provider" subtitle="Credential bersifat write-only dan dienkripsi AES-256-GCM" footer={<><DnaButton variant="outline" onClick={onClose}>Batal</DnaButton><DnaButton variant="primary" loading={saving} onClick={()=>document.getElementById("connection-form")?.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}))}>Simpan koneksi</DnaButton></>}><form id="connection-form" onSubmit={submit} className="space-y-4"><label className="block text-xs font-bold">Brand<select required value={f.brandId} onChange={set("brandId")} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3"><option value="">Pilih brand</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="block text-xs font-bold">Provider<select value={f.provider} onChange={set("provider")} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3">{["META","TIKTOK","YOUTUBE","GA4","GADS"].map(x=><option key={x}>{x}</option>)}</select></label><DnaInput type="password" autoComplete="new-password" label="Access token / secret" value={f.secret} onChange={set("secret")}/><DnaInput label="External account ID" value={f.externalId} onChange={set("externalId")}/><DnaInput label="Scopes (pisahkan koma)" value={f.scopes} onChange={set("scopes")}/><p className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-800">Secret lama tidak pernah dikirim kembali ke browser. Kosongkan secret jika hanya memperbarui konfigurasi non-rahasia.</p></form></DnaDrawer>}
