export enum ProductCategory {
  SKINCARE = "SKINCARE",
  BODYCARE = "BODYCARE",
  BABYCARE = "BABYCARE",
  HAIRCARE = "HAIRCARE",
  DECORATIVE = "DECORATIVE",
  PARFUM = "PARFUM",
  FOOTCARE = "FOOTCARE",
}

export enum WorkflowStatus {
  NEW_LEAD = "NEW_LEAD",
  CONTACTED = "CONTACTED",
  FOLLOW_UP_1 = "FOLLOW_UP_1",
  FOLLOW_UP_2 = "FOLLOW_UP_2",
  FOLLOW_UP_3 = "FOLLOW_UP_3",
  NEGOTIATION = "NEGOTIATION",
  SAMPLE_REQUESTED = "SAMPLE_REQUESTED",
  SAMPLE_SENT = "SAMPLE_SENT",
  SAMPLE_APPROVED = "SAMPLE_APPROVED",
  SPK_SIGNED = "SPK_SIGNED",
  DP_PAID = "DP_PAID",
  PRODUCTION_PLAN = "PRODUCTION_PLAN",
  READY_TO_SHIP = "READY_TO_SHIP",
  WON_DEAL = "WON_DEAL",
  LOST = "LOST",
  ABORTED = "ABORTED",
}

export enum ActivityType {
  CHAT = "CHAT",
  CALL = "CALL",
  MEETING_OFFLINE = "MEETING_OFFLINE",
  MEETING_ONLINE = "MEETING_ONLINE",
}

export enum LostReason {
  PRICE = "PRICE",
  QUALITY = "QUALITY",
  COMPETITOR = "COMPETITOR",
  GHOSTING = "GHOSTING",
  PRICE_ISSUE = "PRICE_ISSUE",
  UNRESPONSIVE = "UNRESPONSIVE",
  PRODUCT_MISMATCH = "PRODUCT_MISMATCH",
  OTHER = "OTHER",
  MOQ_TOO_HIGH = "MOQ_TOO_HIGH",
}
