export const QUERY_KEYS = {
  LEADS: ["leads"] as const,
  LEAD: (id: string) => ["leads", id] as const,
  SAMPLE_REQUESTS: ["sample-requests"] as const,
  SALES_ORDERS: ["sales-orders"] as const,
  INVOICES: ["invoices"] as const,
  FORMULAS: ["formulas"] as const,
  PRODUCTION_PLANS: ["production-plans"] as const,
  WORK_ORDERS: ["work-orders"] as const,
  MACHINES: ["machines"] as const,
  SCHEDULES: ["schedules"] as const,
  FUND_REQUESTS: ["fund-requests"] as const,
  LAB_TEST_RESULTS: ["lab-test-results"] as const,
  NOTIFICATIONS: ["notifications"] as const,
  UNREAD_NOTIFICATIONS: ["notifications", "unread"] as const,
  COA: ["coa"] as const,
  JOURNALS: ["journals"] as const,
  AUDITS: ["audits"] as const,
  MATERIALS: ["materials"] as const,
  SUPPLIERS: ["suppliers"] as const,
  VENDORS: ["vendors"] as const,
  GUESTS: ["guest-logs"] as const,
  BUSSDEV_ANALYTICS: (variant: string) => ["bussdev-analytics", variant] as const,
  PIPELINE_GRANULAR: ["granularPipeline"] as const,
  CASH_TRANSACTIONS: ["cash-transactions"] as const,
  VENDOR_BILLS: ["vendor-bills"] as const,
  PENDING_COSTING: ["pending-costing-batches"] as const,
} as const;

